### ISSUE TITLE
VFS event processing accesses indexes

### ISSUE THREAD

**Issue by hurricup** [Camelcade/Perl5-IDEA#1419]
```
Product: IDEA 171.2014   Action: NewProject   OS: Linux   Java: JetBrains s.r.o 1.8.0_112-release   Reporter: Anonymous   Date: 11.01.2017 21:59  


It's prohibited to access index during event dispatching


java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.intellij.openapi.project.NoAccessDuringPsiEvents.checkCallContext(NoAccessDuringPsiEvents.java:38)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:674)
	at com.intellij.util.indexing.FileBasedIndexImpl.processExceptions(FileBasedIndexImpl.java:840)
	at com.intellij.util.indexing.FileBasedIndexImpl.processValueIterator(FileBasedIndexImpl.java:922)
	at com.intellij.util.indexing.FileBasedIndexImpl.processValuesInScope(FileBasedIndexImpl.java:896)
	at com.intellij.util.indexing.FileBasedIndexImpl.getContainingFiles(FileBasedIndexImpl.java:761)
	at com.intellij.thymeleaf.lang.support.utils.ThymeleafResolveUtil.getThymeleafFilesScope(ThymeleafResolveUtil.java:226)
	at com.intellij.thymeleaf.references.ThymeleafExpressionFilesSearcher.processQuery(ThymeleafExpressionFilesSearcher.java:32)
	at com.intellij.thymeleaf.references.ThymeleafExpressionFilesSearcher.processQuery(ThymeleafExpressionFilesSearcher.java:18)
	at com.intellij.openapi.application.QueryExecutorBase.execute(QueryExecutorBase.java:95)
	at com.intellij.util.ExecutorsQuery.processResults(ExecutorsQuery.java:45)
	at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:79)
	at com.intellij.util.MergeQuery.processSubQuery(MergeQuery.java:85)
	at com.intellij.util.MergeQuery.forEach(MergeQuery.java:57)
	at com.intellij.util.UniqueResultsQuery.process(UniqueResultsQuery.java:66)
	at com.intellij.util.UniqueResultsQuery.forEach(UniqueResultsQuery.java:56)
	at com.intellij.util.UniqueResultsQuery.findAll(UniqueResultsQuery.java:79)
	at com.intellij.util.UniqueResultsQuery.iterator(UniqueResultsQuery.java:91)
	at com.perl5.lang.perl.util.PerlPackageUtil.adjustNestedFiles(PerlPackageUtil.java:508)
	at com.perl5.lang.perl.idea.PerlVirtualFileListener.beforeFileMovement(PerlVirtualFileListener.java:108)
```

**Comment by hurricup** [comment]
Need to re-implement packages adjustments on file operations
