### ISSUE TITLE
Stub and PSI element type mismatch

### ISSUE THREAD

**Issue by slobo** [Camelcade/Perl5-IDEA#1424]
After updating CamelCade to 2016.3.1_9 (from _8 i think) (Idea J Ultimate 2016.3.3, OSX)

Got this error when I Cmd-clicked to navigate (I anonymized file path only)

```
Stub and PSI element type mismatch in Docket.pm: stub PerlSubDefinitionStubImpl, AST USE_STATEMENT; Element(USE_STATEMENT)
 file=Perl5, file.class=class com.perl5.lang.perl.psi.impl.PerlFileImpl, file.lang=Language: Perl5, modStamp=0
 tree consistent
 stub debugInfo=created in getStubTree(), no AST; with backReference
 document before=null
latestIndexedStub=StubTree{myDebugInfo='created from index; with backReference', myRoot=PsiFileStubImpl}1613719940
   same size=true
   debugInfo=created from index; with backReference
 viewProvider=PerlFileViewProvider{myVirtualFile=file:///.../Docket.pm, content=VirtualFileContent{size=16112}}
 viewProvider stamp: 0; file stamp: 0; file modCount: 1484079600000; file length: 16112
 doc saved: true; doc stamp: 0; doc size: 16112; committed: true
in many projects: false
indexing info: indexed at 1484079600000 with size 16112
------------

java.lang.AssertionError: Stub and PSI element type mismatch in Docket.pm: stub PerlSubDefinitionStubImpl, AST USE_STATEMENT; Element(USE_STATEMENT)
 file=Perl5, file.class=class com.perl5.lang.perl.psi.impl.PerlFileImpl, file.lang=Language: Perl5, modStamp=0
 tree consistent
 stub debugInfo=created in getStubTree(), no AST; with backReference
 document before=null
latestIndexedStub=StubTree{myDebugInfo='created from index; with backReference', myRoot=PsiFileStubImpl}1613719940
   same size=true
   debugInfo=created from index; with backReference
 viewProvider=PerlFileViewProvider{myVirtualFile=file:///..../Docket.pm, content=VirtualFileContent{size=16112}}
 viewProvider stamp: 0; file stamp: 0; file modCount: 1484079600000; file length: 16112
 doc saved: true; doc stamp: 0; doc size: 16112; committed: true
in many projects: false
indexing info: indexed at 1484079600000 with size 16112
------------

	at com.intellij.psi.impl.source.PsiFileImpl.reportStubAstMismatch(PsiFileImpl.java:355)
	at com.intellij.psi.impl.source.PsiFileImpl$2.visitNode(PsiFileImpl.java:315)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor.visitComposite(RecursiveTreeElementWalkingVisitor.java:80)
	at com.intellij.psi.impl.source.tree.CompositeElement.acceptTree(CompositeElement.java:160)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor$1.visit(RecursiveTreeElementWalkingVisitor.java:66)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor$1.visit(RecursiveTreeElementWalkingVisitor.java:58)
	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:65)
	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:52)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor.visitNode(RecursiveTreeElementWalkingVisitor.java:85)
	at com.intellij.psi.impl.source.PsiFileImpl$2.visitNode(PsiFileImpl.java:324)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor.visitComposite(RecursiveTreeElementWalkingVisitor.java:80)
	at com.intellij.psi.impl.source.tree.CompositeElement.acceptTree(CompositeElement.java:160)
	at com.intellij.psi.impl.source.PsiFileImpl.calcStubAstBindings(PsiFileImpl.java:298)
	at com.intellij.psi.impl.source.PsiFileImpl.loadTreeElement(PsiFileImpl.java:190)
	at com.intellij.psi.impl.source.PsiFileImpl.calcTreeElement(PsiFileImpl.java:825)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getNode(StubBasedPsiElementBase.java:137)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.getFirstChild(ASTDelegatePsiElement.java:101)
	at com.intellij.psi.impl.PsiElementBase.findChildByClass(PsiElementBase.java:301)
	at com.perl5.lang.perl.psi.mixins.PerlNamespaceDefinitionImplMixin.getNamespaceElement(PerlNamespaceDefinitionImplMixin.java:81)
	at com.perl5.lang.perl.psi.mixins.PerlNamespaceDefinitionImplMixin.getNameIdentifier(PerlNamespaceDefinitionImplMixin.java:88)
	at com.perl5.lang.perl.psi.mixins.PerlNamespaceDefinitionImplMixin.getTextOffset(PerlNamespaceDefinitionImplMixin.java:323)
	at com.intellij.ide.util.EditSourceUtil.getDescriptor(EditSourceUtil.java:58)
	at com.intellij.ide.util.PsiNavigationSupportImpl.getDescriptor(PsiNavigationSupportImpl.java:36)
	at com.intellij.psi.impl.PsiElementBase.navigate(PsiElementBase.java:195)
	at com.intellij.codeInsight.navigation.NavigationUtil.openFileWithPsiElement(NavigationUtil.java:176)
	at com.intellij.codeInsight.navigation.NavigationUtil.activateFileWithPsiElement(NavigationUtil.java:154)
	at com.intellij.ide.actions.SearchEverywhereAction.g(SearchEverywhereAction.java:516)
	at com.intellij.openapi.util.ExecutionCallback.doWhenExecuted(ExecutionCallback.java:100)
	at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
	at com.intellij.ide.actions.SearchEverywhereAction.a(SearchEverywhereAction.java:558)
	at com.intellij.ide.actions.SearchEverywhereAction.access$600(SearchEverywhereAction.java:142)
	at com.intellij.ide.actions.SearchEverywhereAction$16.actionPerformed(SearchEverywhereAction.java:931)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:199)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:215)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:587)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:634)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:204)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:633)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:477)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:657)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by hurricup** [comment]
Please, see: https://twitter.com/CamelcadeIDE/status/826345589877116928
