### ISSUE TITLE
2017.4 - broken highlighting of "unused variables" in "for" loops

### ISSUE THREAD

**Issue by cjelli** [Camelcade/Perl5-IDEA#1646]
Since upgrading to 2017.4 yesterday I am having an issue of vairables being marked as 'unused' in for loops in test (.t) files. I don't observe this behaviour in .pm files:
.pm screenshot (correct)
![correct-for-marking-in-pm](https://user-images.githubusercontent.com/10471722/33511507-932af944-d6d0-11e7-8f80-4816bb9b4e51.png)
.t screenshot (wrong)
![wrong-for-marking-in-t](https://user-images.githubusercontent.com/10471722/33511508-934b9a6e-d6d0-11e7-8a67-6eaf39e1766e.png)

Am I doing something wrong? :)
Also, as you can see, there is no deparse for Test::More xsubs, still.

Thanks!

**Comment by nuxwin** [comment]
Same here... Problem also occurs for while statements. Unused lexical variable: $varname. The problem appear in several places, .pl, .pm files...

**Comment by cjelli** [comment]
Also I see that Data::Dumper and Storable are highlighted as 'unable to find package'.

And while we're at it, I can't regenerate the xsub declarations: it says "The process is already running" - that's for something like 24 hours.
I am using the latest IDEA : 2017.3

Oh, btw:
```
cognac: ~>perl -v

This is perl 5, version 26, subversion 1 (v5.26.1) built for x86_64-linux-thread-multi

Copyright 1987-2017, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

```

**Comment by hurricup** [comment]
@cjelli please, start another issue about data::dumper and storable with code example?

**Comment by hurricup** [comment]
I can't reproduce the problem described. Both code examples works fine in pm/pl/t files:

```Perl
for my $event (@{$game->{evnts}}){
    $EVENT = $event;
}

while(my $row = $sth->fetchrow_hashref()) {
    next unless exists $trafficDb->{$row->{vhost}};
}
```
I need a file with reproducible example.

Also, If you'd be from Russia I'd suggested a mistake in variable name, like russian `o` and latin `o` looks the same but they are different. Same for `e`, `p`, `a`, etc. Could this be the same problem? Could compile without a `strict` pragma

**Comment by cjelli** [comment]
There are no mistakes in variable names, I never used anything outside ASCII in them.
I am uploading the test file that has all the problems I described:
1) $team and $player are incorrectly highlighted
2) Data::Dumper and Storable are incorrectly highlighted (although I'll open an issue for them with a screenshot too)
3) MongoDB and Test::More subs are not deparsed.

[165-add-all-players-coaches-officials.txt](https://github.com/Camelcade/Perl5-IDEA/files/1523959/165-add-all-players-coaches-officials.txt)
The file was renamed to txt because of GitHub's limitation.

**Comment by hurricup** [comment]
@cjelli reproduced with your sample.

**Comment by nuxwin** [comment]
@hurricup 

This seem to occurs mosthly inside eval block.

**Comment by cjelli** [comment]
I think it's both eval {} and sub {} blocks

Yes, I checked, in the same file, outside the sub {} block, the error does not happen.
It also does not happen within the mere {} blocks.

**Comment by hurricup** [comment]
The problem is expression nesting: `do`, `eval` and anon `sub`. Working on.

**Comment by hurricup** [comment]
Feel free to rebuild from master and try. (see the README)

**Comment by nuxwin** [comment]
@hurricup 

OUCH... That was not a small issue as I can see regarding all your changes... Well, I'll give a try.
Thank for your great job here.

**Comment by nuxwin** [comment]
@hurricup 

Unfortunatelly, I cannot build...

```
nuxwin@dev:/github/camelcade/Perl5-IDEA$ ./gradlew buildPlugin
Downloading https://services.gradle.org/distributions/gradle-3.3-all.zip

Exception in thread "main" javax.net.ssl.SSLException: java.security.ProviderException: java.security.InvalidKeyException: EC parameters error
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1914)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1872)
        at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1855)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1376)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1353)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1348)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
        at org.gradle.wrapper.Download.download(Download.java:44)
        at org.gradle.wrapper.Install$1.call(Install.java:61)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: java.security.ProviderException: java.security.InvalidKeyException: EC parameters error
        at sun.security.pkcs11.P11Key$P11ECPublicKey.getEncodedInternal(P11Key.java:1024)
        at sun.security.pkcs11.P11Key.equals(P11Key.java:158)
        at java.util.ArrayList.indexOf(ArrayList.java:298)
        at java.util.ArrayList.contains(ArrayList.java:281)
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:239)
        at sun.security.validator.Validator.validate(Validator.java:260)
        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:326)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:126)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1459)
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:213)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:961)
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:897)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1033)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1342)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1369)
        ... 13 more
Caused by: java.security.InvalidKeyException: EC parameters error
        at sun.security.ec.ECParameters.getAlgorithmParameters(ECParameters.java:284)
        at sun.security.ec.ECPublicKeyImpl.<init>(ECPublicKeyImpl.java:59)
        at sun.security.pkcs11.P11Key$P11ECPublicKey.getEncodedInternal(P11Key.java:1021)
        ... 28 more
Caused by: java.security.NoSuchProviderException: no such provider: SunEC
        at sun.security.jca.GetInstance.getService(GetInstance.java:83)
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:206)
        at java.security.Security.getImpl(Security.java:697)
        at java.security.AlgorithmParameters.getInstance(AlgorithmParameters.java:199)
        at sun.security.ec.ECParameters.getAlgorithmParameters(ECParameters.java:279)
        ... 30 more
```

**Comment by hurricup** [comment]
Seems your local java is not configured, see https://github.com/facebook/react-native/issues/14091#issuecomment-303027833

**Comment by hurricup** [comment]
@cjelli don't forget to create an issue about deparsing

**Comment by nuxwin** [comment]
@hurricup 
Thanks. This was an issue with java-7-openjdk-amd64 issue. I've switched to java-8-oracle and the problem has been solved:

```shell
nuxwin@dev:/github/camelcade/Perl5-IDEA$ LANG=C update-alternatives --config java
There are 2 choices for the alternative java (providing /usr/bin/java).

  Selection    Path                                            Priority   Status
------------------------------------------------------------
  0            /usr/lib/jvm/java-8-oracle/jre/bin/java          1081      auto mode
  1            /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java   1071      manual mode
* 2            /usr/lib/jvm/java-8-oracle/jre/bin/java          1081      manual mode

Press enter to keep the current choice[*], or type selection number: 
nuxwin@dev:/github/camelcade/Perl5-IDEA$ 
```

```shell
BUILD SUCCESSFUL
```

*BTW:* Building your plugin requires a lot data download (dependencies)... Whatever. I'll now install the plugin and see if the issue is fixed. I'll let you know.

**Comment by nuxwin** [comment]
@hurricup 

I confirm that the issue is solved.

BTW: I cannot reproduce the issue regarding XSubs deparsing..

**Comment by nuxwin** [comment]
@hurricup @cjelli 

Issue regarding Xsubs deparsing created: https://github.com/Camelcade/Perl5-IDEA/issues/1650

**Comment by hurricup** [comment]
@nuxwin True, but gradle caches them, so there are lot of downloading in very first time or some versions change.
