### ISSUE TITLE
Mojolicious plugin indexing error

### ISSUE THREAD

**Issue by huckeduster** [Camelcade/Perl5-IDEA#1849]
My setup:

* PyCharm 2018.3 (Community Edition)
Build #PC-183.4284.139, built on November 20, 2018
JRE: 1.8.0_152-release-1343-b15 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6
* Perl 5.24.2 via plenv
* java version "1.8.0_192"

Error that occurs:

1. Updated to latest Pycharm version, Camelcade's latest Perl Plugins (Perl, Mojolicious, Template Toolkit all v2018.3.1), removed and re-added the configured Perl interpreter, updated Camelcade Debugger plugin to newest version.
1. Opened a Perl project I'm working on.
1. Got these stacktraces:

```
Error while indexing /Users/*********/.plenv/versions/5.24.2-*********/lib/perl5/site_perl/5.24.2/Mojolicious/resources/templates/mojo/debug.html.ep
To reindex this file IDEA has to be restarted

java.lang.IllegalAccessError: tried to access method com.perl5.lang.perl.parser.PerlParserGenerated.block_content(Lcom/intellij/lang/PsiBuilder;I)Z from class com.perl5.lang.perl.parser.MojoliciousParser
	at com.perl5.lang.perl.parser.MojoliciousParser.parseTerm(MojoliciousParser.java:60)
	at com.perl5.lang.perl.parser.PerlParserUtil.parseParserExtensionTerm(PerlParserUtil.java:378)
	at com.perl5.lang.perl.parser.PerlParserGenerated.term_expr(PerlParserGenerated.java:6202)
	at com.perl5.lang.perl.parser.PerlParserGenerated.expr(PerlParserGenerated.java:5645)
	at com.perl5.lang.perl.parser.PerlParserGenerated.expr_0(PerlParserGenerated.java:5677)
	at com.perl5.lang.perl.parser.PerlParserGenerated.expr(PerlParserGenerated.java:5647)
	at com.perl5.lang.perl.parser.PerlParserGenerated.normal_statement(PerlParserGenerated.java:2771)
	at com.perl5.lang.perl.parser.PerlParserGenerated.statement_body(PerlParserGenerated.java:4187)
	at com.perl5.lang.perl.parser.PerlParserGenerated.statement_3(PerlParserGenerated.java:4175)
	at com.perl5.lang.perl.parser.PerlParserGenerated.statement(PerlParserGenerated.java:4165)
	at com.perl5.lang.perl.parser.PerlParserGenerated.statement_item(PerlParserGenerated.java:4214)
	at com.perl5.lang.perl.parser.PerlParserGenerated.file_item_1(PerlParserGenerated.java:1370)
	at com.perl5.lang.perl.parser.PerlParserGenerated.file_item(PerlParserGenerated.java:1346)
	at com.perl5.lang.perl.parser.PerlParserGenerated.file_items(PerlParserGenerated.java:1399)
	at com.perl5.lang.perl.parser.PerlParserImpl.parseFileContents(PerlParserImpl.java:112)
	at com.perl5.lang.perl.parser.PerlParserUtil.parseFileContent(PerlParserUtil.java:383)
	at com.perl5.lang.perl.parser.PerlParserGenerated.root(PerlParserGenerated.java:3816)
	at com.perl5.lang.perl.parser.PerlParserGenerated.parse_root_(PerlParserGenerated.java:399)
	at com.perl5.lang.perl.parser.PerlParserGenerated.parseLight(PerlParserGenerated.java:393)
	at com.perl5.lang.perl.parser.PerlParserGenerated.parse(PerlParserGenerated.java:18)
	at com.perl5.lang.perl.psi.stubs.PerlFileElementType.doParseContents(PerlFileElementType.java:43)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:49)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.lambda$ensureParsed$0(LazyParseableElement.java:192)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:553)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:191)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getLastChildNode(LazyParseableElement.java:251)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getLastChildNode(LazyParseableElement.java:39)
	at com.intellij.psi.stubs.DefaultStubBuilder$StubBuildingWalkingVisitor.pushChildren(DefaultStubBuilder.java:112)
	at com.intellij.psi.stubs.DefaultStubBuilder$StubBuildingWalkingVisitor.visitNode(DefaultStubBuilder.java:82)
	at com.intellij.psi.stubs.DefaultStubBuilder$StubBuildingWalkingVisitor.buildStubTree(DefaultStubBuilder.java:72)
	at com.intellij.psi.stubs.DefaultStubBuilder.buildStubTreeFor(DefaultStubBuilder.java:50)
	at com.intellij.psi.stubs.DefaultStubBuilder.buildStubTree(DefaultStubBuilder.java:39)
	at com.intellij.psi.stubs.StubTreeBuilder.buildStubTree(StubTreeBuilder.java:84)
	at com.intellij.psi.stubs.StubUpdatingIndex$3.lambda$map$0(StubUpdatingIndex.java:238)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:943)
	at com.intellij.psi.stubs.StubUpdatingIndex$3.map(StubUpdatingIndex.java:220)
	at com.intellij.psi.stubs.StubUpdatingIndex$3.map(StubUpdatingIndex.java:202)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:276)
	at com.intellij.util.indexing.VfsAwareMapReduceIndex.calculateUpdateData(VfsAwareMapReduceIndex.java:83)
	at com.intellij.util.indexing.impl.MapReduceIndex.update(MapReduceIndex.java:216)
	at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1668)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$27(FileBasedIndexImpl.java:1596)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:522)
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1555)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1543)
	at com.intellij.util.indexing.UnindexedFilesUpdater.lambda$indexFiles$0(UnindexedFilesUpdater.java:110)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.lambda$run$0(CacheUpdateRunner.java:230)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1168)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.lambda$run$1(CacheUpdateRunner.java:246)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:243)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

```
java.lang.IllegalAccessError: tried to access method com.perl5.lang.perl.parser.PerlParserGenerated.block_content(Lcom/intellij/lang/PsiBuilder;I)Z from class com.perl5.lang.perl.parser.MojoliciousParser
	at com.perl5.lang.perl.parser.MojoliciousParser.parseTerm(MojoliciousParser.java:60)
	at com.perl5.lang.perl.parser.PerlParserUtil.parseParserExtensionTerm(PerlParserUtil.java:378)
	at com.perl5.lang.perl.parser.PerlParserGenerated.term_expr(PerlParserGenerated.java:6202)
	at com.perl5.lang.perl.parser.PerlParserGenerated.expr(PerlParserGenerated.java:5645)
	at com.perl5.lang.perl.parser.PerlParserGenerated.expr_0(PerlParserGenerated.java:5677)
	at com.perl5.lang.perl.parser.PerlParserGenerated.expr(PerlParserGenerated.java:5647)
	at com.perl5.lang.perl.parser.PerlParserGenerated.normal_statement(PerlParserGenerated.java:2771)
	at com.perl5.lang.perl.parser.PerlParserGenerated.statement_body(PerlParserGenerated.java:4187)
	at com.perl5.lang.perl.parser.PerlParserGenerated.statement_3(PerlParserGenerated.java:4175)
	at com.perl5.lang.perl.parser.PerlParserGenerated.statement(PerlParserGenerated.java:4165)
	at com.perl5.lang.perl.parser.PerlParserGenerated.statement_item(PerlParserGenerated.java:4214)
	at com.perl5.lang.perl.parser.PerlParserGenerated.file_item_1(PerlParserGenerated.java:1370)
	at com.perl5.lang.perl.parser.PerlParserGenerated.file_item(PerlParserGenerated.java:1346)
	at com.perl5.lang.perl.parser.PerlParserGenerated.file_items(PerlParserGenerated.java:1399)
	at com.perl5.lang.perl.parser.PerlParserImpl.parseFileContents(PerlParserImpl.java:112)
	at com.perl5.lang.perl.parser.PerlParserUtil.parseFileContent(PerlParserUtil.java:383)
	at com.perl5.lang.perl.parser.PerlParserGenerated.root(PerlParserGenerated.java:3816)
	at com.perl5.lang.perl.parser.PerlParserGenerated.parse_root_(PerlParserGenerated.java:399)
	at com.perl5.lang.perl.parser.PerlParserGenerated.parseLight(PerlParserGenerated.java:393)
	at com.perl5.lang.perl.parser.PerlParserGenerated.parse(PerlParserGenerated.java:18)
	at com.perl5.lang.perl.psi.stubs.PerlFileElementType.doParseContents(PerlFileElementType.java:43)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:49)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.lambda$ensureParsed$0(LazyParseableElement.java:192)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:553)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:191)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getLastChildNode(LazyParseableElement.java:251)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getLastChildNode(LazyParseableElement.java:39)
	at com.intellij.psi.stubs.DefaultStubBuilder$StubBuildingWalkingVisitor.pushChildren(DefaultStubBuilder.java:112)
	at com.intellij.psi.stubs.DefaultStubBuilder$StubBuildingWalkingVisitor.visitNode(DefaultStubBuilder.java:82)
	at com.intellij.psi.stubs.DefaultStubBuilder$StubBuildingWalkingVisitor.buildStubTree(DefaultStubBuilder.java:72)
	at com.intellij.psi.stubs.DefaultStubBuilder.buildStubTreeFor(DefaultStubBuilder.java:50)
	at com.intellij.psi.stubs.DefaultStubBuilder.buildStubTree(DefaultStubBuilder.java:39)
	at com.intellij.psi.stubs.StubTreeBuilder.buildStubTree(StubTreeBuilder.java:84)
	at com.intellij.psi.stubs.StubUpdatingIndex$3.lambda$map$0(StubUpdatingIndex.java:238)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:943)
	at com.intellij.psi.stubs.StubUpdatingIndex$3.map(StubUpdatingIndex.java:220)
	at com.intellij.psi.stubs.StubUpdatingIndex$3.map(StubUpdatingIndex.java:202)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:276)
	at com.intellij.util.indexing.VfsAwareMapReduceIndex.calculateUpdateData(VfsAwareMapReduceIndex.java:83)
	at com.intellij.util.indexing.impl.MapReduceIndex.update(MapReduceIndex.java:216)
	at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1668)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$27(FileBasedIndexImpl.java:1596)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:522)
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1555)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1543)
	at com.intellij.util.indexing.FileBasedIndexImpl.processRefreshedFile(FileBasedIndexImpl.java:1522)
	at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1686)
	at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1683)
	at com.intellij.util.indexing.UpdateTask.process(UpdateTask.java:76)
	at com.intellij.util.indexing.UpdateTask.processAll(UpdateTask.java:46)
	at com.intellij.util.indexing.FileBasedIndexImpl.forceUpdate(FileBasedIndexImpl.java:1705)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:739)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:705)
	at com.intellij.psi.stubs.StubIndexImpl.doProcessStubs(StubIndexImpl.java:300)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:276)
	at com.intellij.psi.stubs.StubIndex.processElements(StubIndex.java:65)
	at com.perl5.lang.perl.psi.stubs.namespaces.PerlNamespaceIndex.processNamespaces(PerlNamespaceIndex.java:51)
	at com.perl5.lang.perl.util.PerlPackageUtil.processNamespaces(PerlPackageUtil.java:334)
	at com.perl5.lang.perl.util.PerlPackageUtil.getNamespaceDefinitions(PerlPackageUtil.java:305)
	at com.perl5.lang.perl.util.PerlPackageUtil.getNamespaceDefinitions(PerlPackageUtil.java:298)
	at com.perl5.lang.perl.util.PerlPackageUtil.isDeprecated(PerlPackageUtil.java:149)
	at com.perl5.lang.perl.psi.impl.PerlNamespaceElementImpl.isDeprecated(PerlNamespaceElementImpl.java:113)
	at com.perl5.lang.perl.idea.inspections.PerlDeprecatedInspection$1.visitNamespaceElement(PerlDeprecatedInspection.java:84)
	at com.perl5.lang.perl.psi.impl.PerlNamespaceElementImpl.accept(PerlNamespaceElementImpl.java:63)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:75)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:63)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:292)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$5(LocalInspectionsPass.java:260)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:126)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:115)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$6(LocalInspectionsPass.java:257)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1168)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:222)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

Any idea how to avoid these stacktraces (of course I restarted Pycharm a couple of times) besides disables Mojolicious plugin?

Thanks in advance
Andre

**Comment by hurricup** [comment]
Could you please also attach file in question
