### ISSUE TITLE
Invalid method access exception

### ISSUE THREAD

**Issue by hurricup** [Camelcade/Perl5-IDEA#1857]
Build: IU-183.4284.148
OS: Mac OS X x86_64 10.14.1
Java Vendor: JetBrains s.r.o
Java Version: 1.8.0_152-release
Java Arch: 64 bit
Java Runtime Version: 1.8.0_152-release-1343-b15
Perl Plugin Version: 2018.3.3
Description: <none>

```
IdeaLoggingEvent[message=null, throwable=com.intellij.psi.PsiInvalidElementAccessException: Element class com.intellij.psi.impl.source.tree.CompositeElement of type SUB_DECLARATION (class com.perl5.lang.perl.psi.stubs.subsdeclarations.PerlSubDeclarationElementType)
 at com.intellij.psi.PsiInvalidElementAccessException.createByNode(PsiInvalidElementAccessException.java:96)
 at com.intellij.psi.impl.source.SubstrateRef$2.getContainingFile(SubstrateRef.java:101)
 at com.intellij.extapi.psi.StubBasedPsiElementBase.getContainingFile(StubBasedPsiElementBase.java:252)
 at com.perl5.lang.perl.psi.mixins.PerlSubDeclarationBase.isXSub(PerlSubDeclarationBase.java:71)
 at com.perl5.lang.perl.psi.mixins.PerlSubDeclarationBase.getIcon(PerlSubDeclarationBase.java:49)
 at com.perl5.lang.perl.idea.presentations.PerlItemPresentationBase.getIcon(PerlItemPresentationBase.java:56)
 at com.intellij.ide.projectView.PresentationData.updateFrom(PresentationData.java:187)
 at com.intellij.ide.util.treeView.smartTree.TreeElementWrapper.update(TreeElementWrapper.java:42)
 at com.intellij.ide.util.treeView.PresentableNodeDescriptor.getUpdatedPresentation(PresentableNodeDescriptor.java:89)
 at com.intellij.ide.util.treeView.PresentableNodeDescriptor.update(PresentableNodeDescriptor.java:41)
 at com.intellij.ui.tree.StructureTreeModel$Node.update(StructureTreeModel.java:442)
 at com.intellij.ui.tree.StructureTreeModel$Node.access$200(StructureTreeModel.java:410)
 at com.intellij.ui.tree.StructureTreeModel.lambda$getChildren$14(StructureTreeModel.java:314)
 at java.util.ArrayList.forEach(ArrayList.java:1251)
 at com.intellij.ui.tree.StructureTreeModel.getChildren(StructureTreeModel.java:314)
 at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.getNode(AsyncTreeModel.java:559)
 at com.intellij.ui.tree.AsyncTreeModel$ObsolescentCommand.get(AsyncTreeModel.java:453)
 at com.intellij.ui.tree.AsyncTreeModel$ObsolescentCommand.get(AsyncTreeModel.java:419)
 at com.intellij.util.concurrency.Command$Processor.lambda$process$1(Command.java:48)
 at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1168)
 at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:70)
 at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:123)
 at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
 at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
 at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
 at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
 at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
 at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:112)
 at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:70)
 at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:152)
 at com.intellij.util.concurrency.Invoker.lambda$invokeLater$0(Invoker.java:90)
 at com.intellij.util.concurrency.Invoker$BackgroundThread.lambda$offer$0(Invoker.java:318)
 at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:227)
 at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:26)
 at com.intellij.util.concurrency.BoundedTaskExecutor$2$1.run(BoundedTaskExecutor.java:200)
 at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:229)
 at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:194)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 at java.lang.Thread.run(Thread.java:745)
]
```

**Comment by hurricup** [comment]
Looks like ide problem

**Comment by hurricup** [comment]
Changes related to #1869
