### ISSUE TITLE
Exception in SearchEverywhere

### ISSUE THREAD

**Issue by hurricup** [Camelcade/Perl5-IDEA#1858]
Build: PS-183.4284.150
OS: Windows 7 amd64 6.1
Java Vendor: JetBrains s.r.o
Java Version: 1.8.0_152-release
Java Arch: 64 bit
Java Runtime Version: 1.8.0_152-release-1343-b15
Perl Plugin Version: 2018.3.3
Plugin Version: 3.0.0-pre4
Description: <none>

```
IdeaLoggingEvent[message=Details: Current thread: Thread[SE-SearchTask,4,Idea Thread Group] 1247382801
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0 2018.3#PS-183.4284.150 PhpStorm, eap:false, os:Windows 7 6.1, java-version:JetBrains s.r.o 1.8.0_152-release-1343-b15,6,Idea Thread Group] 739481230, throwable=java.lang.Throwable: Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
 at com.intellij.openapi.diagnostic.Logger.error(Logger.java:156)
 at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1090)
 at com.intellij.psi.impl.source.PsiFileImpl.assertReadAccessAllowed(PsiFileImpl.java:183)
 at com.intellij.psi.impl.source.PsiFileImpl.getStubTree(PsiFileImpl.java:591)
 at com.intellij.psi.impl.source.SpineRef.getStub(SpineRef.java:32)
 at com.intellij.extapi.psi.StubBasedPsiElementBase.getStub(StubBasedPsiElementBase.java:362)
 at com.perl5.lang.perl.psi.mixins.PerlNamespaceDefinitionMixin.getPackageName(PerlNamespaceDefinitionMixin.java:103)
 at com.perl5.lang.perl.psi.mixins.PerlNamespaceDefinitionMixin.getName(PerlNamespaceDefinitionMixin.java:79)
 at com.intellij.ide.actions.searcheverywhere.PsiElementsEqualityProvider.convertToFileIsPossible(PsiElementsEqualityProvider.java:64)
 at com.intellij.ide.actions.searcheverywhere.PsiElementsEqualityProvider.isSameFile(PsiElementsEqualityProvider.java:51)
 at com.intellij.ide.actions.searcheverywhere.PsiElementsEqualityProvider.compareItems(PsiElementsEqualityProvider.java:29)
 at com.intellij.ide.actions.searcheverywhere.SEResultsEqualityProvider$1.lambda$compareItems$0(SEResultsEqualityProvider.java:34)
 at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
 at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
 at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
 at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
 at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
 at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
 at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
 at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
 at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
 at com.intellij.ide.actions.searcheverywhere.SEResultsEqualityProvider$1.compareItems(SEResultsEqualityProvider.java:36)
 at com.intellij.ide.actions.searcheverywhere.MultithreadSearcher$ResultsAccumulator.lambda$getActionsWithOtherElements$0(MultithreadSearcher.java:241)
 at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
 at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1376)
 at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
 at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
 at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1620)
 at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
 at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
 at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
 at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
 at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
 at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
 at com.intellij.ide.actions.searcheverywhere.MultithreadSearcher$ResultsAccumulator.getActionsWithOtherElements(MultithreadSearcher.java:240)
 at com.intellij.ide.actions.searcheverywhere.MultithreadSearcher$FullSearchResultsAccumulator.addElement(MultithreadSearcher.java:350)
 at com.intellij.ide.actions.searcheverywhere.MultithreadSearcher$ContributorSearchTask.lambda$run$0(MultithreadSearcher.java:191)
 at com.intellij.ide.actions.searcheverywhere.RecentFilesSEContributor.fetchElements(RecentFilesSEContributor.java:90)
 at com.intellij.ide.actions.searcheverywhere.MultithreadSearcher$ContributorSearchTask.run(MultithreadSearcher.java:182)
 at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:229)
 at com.intellij.util.ConcurrencyUtil$3.run(ConcurrencyUtil.java:215)
 at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 at java.lang.Thread.run(Thread.java:745)
]
```

**Comment by hurricup** [comment]
IDE problem, fixed
