### ISSUE TITLE
Wrong thread on cleaning cahes

### ISSUE THREAD

**Issue by hurricup** [Camelcade/Perl5-IDEA#1865]
Build: DB-183.4284.162
OS: Windows 7 amd64 6.1
Java Vendor: JetBrains s.r.o
Java Version: 1.8.0_152-release
Java Arch: 64 bit
Java Runtime Version: 1.8.0_152-release-1343-b15
Perl Plugin Version: 2018.3.3
Description: <none>

```
IdeaLoggingEvent[message=null, throwable=java.lang.Throwable: This supposed to be invoked from pooled thread
 at com.intellij.openapi.diagnostic.Logger.error(Logger.java:134)
…
 at com.intellij.openapi.diagnostic.Logger.error(Logger.java:134)
 at com.perl5.lang.perl.idea.sdk.host.PerlHostCacheCleaner.runActivity(PerlHostCacheCleaner.java:54)
 at com.intellij.ide.startup.impl.StartupManagerImpl.runAndMeasure(StartupManagerImpl.java:164)
 at com.intellij.ide.startup.impl.StartupManagerImpl.logActivityDuration(StartupManagerImpl.java:150)
 at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$runPostStartupActivitiesFromExtensions$1(StartupManagerImpl.java:138)
 at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:356)
 at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivitiesFromExtensions(StartupManagerImpl.java:140)
 at com.intellij.openapi.project.impl.ProjectManagerImpl.lambda$openProject$8(ProjectManagerImpl.java:409)
 at com.intellij.openapi.project.impl.ProjectManagerImpl.loadProjectUnderProgress(ProjectManagerImpl.java:440)
 at com.intellij.openapi.project.impl.ProjectManagerImpl.openProject(ProjectManagerImpl.java:423)
 at com.intellij.platform.PlatformProjectOpenProcessor.doOpenProject(PlatformProjectOpenProcessor.java:254)
 at com.intellij.database.ide.DatabaseProjectUtil.openOrCreateProjectInner(DatabaseProjectUtil.java:87)
 at com.intellij.database.ide.DatabaseProjectUtil.lambda$openOrCreateProject$0(DatabaseProjectUtil.java:68)
 at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
 at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
 at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
 at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:192)
 at com.intellij.database.ide.DatabaseProjectUtil.openOrCreateProject(DatabaseProjectUtil.java:67)
 at com.intellij.database.ide.DatabaseRecentProjectManager.openDefaultProject(DatabaseRecentProjectManager.java:95)
 at com.intellij.database.ide.DatabaseRecentProjectManager.doReopenLastProject(DatabaseRecentProjectManager.java:55)
 at com.intellij.ide.RecentProjectsManagerBase$MyAppLifecycleListener.appStarting(RecentProjectsManagerBase.java:742)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:498)
 at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
 at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:397)
 at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:358)
 at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:347)
 at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:324)
 at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:29)
 at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:196)
 at com.sun.proxy.$Proxy57.appStarting(Unknown Source)
 at com.intellij.idea.IdeaApplication$IdeStarter.lambda$main$1(IdeaApplication.java:372)
 at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
 at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)
 at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:120)
 at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
 at com.intellij.idea.IdeaApplication$IdeStarter.main(IdeaApplication.java:370)
 at com.intellij.idea.IdeaApplication.lambda$run$1(IdeaApplication.java:211)
 at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
 at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:211)
 at com.intellij.idea.IdeaApplication.lambda$initApplication$0(IdeaApplication.java:74)
 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
 at java.awt.EventQueue.access$500(EventQueue.java:98)
 at java.awt.EventQueue$3.run(EventQueue.java:715)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
 at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:342)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
]
```

**Comment by hurricup** [comment]
DataGrip bug
