### ISSUE TITLE
Freeze when selecting non-local Perl interpreter 

### ISSUE THREAD

**Issue by asdfg** [Camelcade/Perl5-IDEA#1932]
I'm trying to use the Perl interpreter from my CentOS 7 Docker image. I'm able to select the container and navigate its filesystem, but once I select the interpreter (perlhost:///usr/bin/perl), I'm unable to leave the file selection window. Neither "OK" nor "Cancel" work and I need to kill IntelliJ via the task manager.

Windows 10 Professional
IntelliJ IDEA 2019.1 Ultimate EAP
Perl5 + Docker plugin 191.5701
Docker: Version 2.0.0.2 (30215), stable, Build: 0b030e1

Full stacktrace attached. [stacktrace.txt](https://github.com/Camelcade/Perl5-IDEA/files/2919692/stacktrace.txt)

```
2019-02-28 INFO - idea.execution.PerlCommandLine - Executing: **docker exec intellijPerl_filesystem_mycontainer_latest_1551392093538 ls -LAs --classify /usr** 
2019-02-28 INFO - idea.execution.PerlCommandLine -   environment: {} (+CONSOLE) 
2019-02-28 INFO - idea.execution.PerlCommandLine -   host = local; vm = null; pty = false; charset: windows-1252 
2019-02-28 WARN - impl.local.LocalFileSystemBase - Invalid path: /usr 
2019-02-28 ERROR - api.util.objectTree.ObjectTree - null 
java.lang.NullPointerException
	at com.intellij.openapi.vfs.impl.local.LocalFileSystemImpl.replaceWatchedRoots(LocalFileSystemImpl.java:278)

	at com.intellij.openapi.vfs.LocalFileSystem.removeWatchedRoots(LocalFileSystem.java:84)

	at com.intellij.openapi.fileChooser.ex.FileChooserDialogImpl.dispose(FileChooserDialogImpl.java:368)
. . .
2019-02-28 ERROR - api.util.objectTree.ObjectTree - IntelliJ IDEA 2019.1 EAP  Build #IU-191.5849.21 
2019-02-28 ERROR - api.util.objectTree.ObjectTree - JDK: 1.8.0_202-release; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2019-02-28 ERROR - api.util.objectTree.ObjectTree - OS: Windows 10 
2019-02-28 ERROR - api.util.objectTree.ObjectTree - Plugin to blame: Perl version: 191.5701 
```

Note that the Docker exec command above runs without issue from the Windows cmd prompt. Also, this error only occurs if a folder is opened in the file browser. If I stay in my container's root, without opening any directories, I'm able to close/cancel the interpreter selection prompt as expected.

**Comment by hurricup** [comment]
Please, provide a `Dockerfile` to test on if possible. Will investigate this.

**Comment by asdfg** [comment]
> Please, provide a `Dockerfile` to test on if possible. Will investigate this.

Thanks - here what I used. I also see the same issue on a clean Ubuntu:latest (which, unlike CentOS, has Perl preinstalled).
```
FROM centos:7
RUN yum -y groupinstall 'Development Tools'
RUN yum -y install perl perl-cpan
```

My Docker version is:
Version 2.0.0.2 (30215)
Channel: stable
Build: 0b030e1

**Comment by hurricup** [comment]
It's IDE problem with FileChooser. Reported it.

**Comment by hurricup** [comment]
Should work fine in the next IDEA EAP.

**Comment by hurricup** [comment]
https://github.com/JetBrains/intellij-community/commit/7ef9daac59e195b5c919512ef38713a108ed6a4d
