### ISSUE TITLE
Exception in the bradcrumbs provider 

### ISSUE THREAD

**Issue by hurricup** [Camelcade/Perl5-IDEA#2017]
Build: PS-191.6183.95
OS: Windows 10 amd64 10.0
Java Vendor: JetBrains s.r.o
Java Version: 1.8.0_202-release
Java Arch: 64 bit
Java Runtime Version: 1.8.0_202-release-1483-b39
Perl Plugin Version: 2019.1
Description: <none>

```
IdeaLoggingEvent[message=null, throwable=java.lang.NoSuchFieldError: ARRAY
at com.perl5.lang.perl.idea.ui.breadcrumbs.PerlBreadcrumbsProvider.getLanguages(PerlBreadcrumbsProvider.java:37)
at com.intellij.ui.breadcrumbs.BreadcrumbsUtil.getInfoProvider(BreadcrumbsUtil.java:27)
at com.intellij.xml.breadcrumbs.BreadcrumbsUtilEx.findProvider(BreadcrumbsUtilEx.java:45)
at com.intellij.xml.breadcrumbs.BreadcrumbsUtilEx.findProvider(BreadcrumbsUtilEx.java:32)
at com.intellij.xml.breadcrumbs.BreadcrumbsUtilEx.findProvider(BreadcrumbsUtilEx.java:24)
at com.intellij.xml.breadcrumbs.PsiFileBreadcrumbsCollector.isShownForFile(PsiFileBreadcrumbsCollector.java:48)
at com.intellij.xml.breadcrumbs.BreadcrumbsInitializingActivity.isSuitable(BreadcrumbsInitializingActivity.java:116)
at com.intellij.xml.breadcrumbs.BreadcrumbsInitializingActivity.reinitBreadcrumbsComponent(BreadcrumbsInitializingActivity.java:90)
at com.intellij.xml.breadcrumbs.BreadcrumbsInitializingActivity.access$200(BreadcrumbsInitializingActivity.java:29)
at com.intellij.xml.breadcrumbs.BreadcrumbsInitializingActivity$MyVirtualFileListener.propertyChanged(BreadcrumbsInitializingActivity.java:69)
at sun.reflect.GeneratedMethodAccessor123.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:132)
at com.intellij.util.EventDispatcher.access$000(EventDispatcher.java:26)
at com.intellij.util.EventDispatcher$1.invoke(EventDispatcher.java:90)
at com.sun.proxy.$Proxy23.propertyChanged(Unknown Source)
at com.intellij.openapi.vfs.impl.BulkVirtualFileListenerAdapter.fireAfter(BulkVirtualFileListenerAdapter.java:93)
at com.intellij.openapi.vfs.impl.BulkVirtualFileListenerAdapter.after(BulkVirtualFileListenerAdapter.java:56)
at sun.reflect.GeneratedMethodAccessor124.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:114)
at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:393)
at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:354)
at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:343)
at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:320)
at com.intellij.util.messages.impl.MessageBusImpl.access$100(MessageBusImpl.java:29)
at com.intellij.util.messages.impl.MessageBusImpl$1.invoke(MessageBusImpl.java:192)
at com.sun.proxy.$Proxy22.after(Unknown Source)
at com.intellij.util.FileContentUtilCore.lambda$reparseFiles$0(FileContentUtilCore.java:65)
at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1054)
at com.intellij.util.FileContentUtilCore.reparseFiles(FileContentUtilCore.java:55)
at com.intellij.util.FileContentUtil.reparseFiles(FileContentUtil.java:70)
at com.intellij.util.FileContentUtil.reparseOpenedFiles(FileContentUtil.java:75)
at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
at java.awt.EventQueue.access$500(EventQueue.java:98)
at java.awt.EventQueue$3.run(EventQueue.java:715)
at java.awt.EventQueue$3.run(EventQueue.java:709)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:747)
at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:696)
at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)]
```

**Comment by hurricup** [comment]
This looks like something broken in PS
