### ISSUE TITLE
Problem with inference in watch light editor

### ISSUE THREAD

**Issue by hurricup** [Camelcade/Perl5-IDEA#2079]
Build: IU-192.5438.14
OS: Linux amd64 4.15.0-54-generic
Java Vendor: JetBrains s.r.o
Java Version: 11.0.3
Java Arch: 64 bit
Java Runtime Version: 11.0.3+12-b304.2
Perl Plugin Version: 192.5438.14-EAP-SNAPSHOT
Description: <none>

```
IdeaLoggingEvent[message=null, throwable=java.lang.Throwable: Unable to find an instruction for class com.perl5.lang.perl.psi.impl.PerlFileImpl; join ',', @_;; (0,13); LightVirtualFile: /file.dummy
at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
at com.perl5.lang.perl.psi.utils.PerlResolveUtil.getValueFromControlFlow(PerlResolveUtil.java:257)
at com.perl5.lang.perl.psi.utils.PerlResolveUtil.lambda$getValueFromControlFlow$1(PerlResolveUtil.java:280)
at com.intellij.codeInsight.controlflow.ControlFlowUtil.iterate(ControlFlowUtil.java:129)
at com.intellij.codeInsight.controlflow.ControlFlowUtil.iteratePrev(ControlFlowUtil.java:111)
at com.perl5.lang.perl.psi.utils.PerlResolveUtil.getValueFromControlFlow(PerlResolveUtil.java:265)
at com.perl5.lang.perl.psi.utils.PerlResolveUtil.inferVariableValue(PerlResolveUtil.java:192)
at com.perl5.lang.perl.psi.mixins.PerlVariableMixin.computePerlValue(PerlVariableMixin.java:88)
at com.perl5.lang.perl.idea.codeInsight.typeInference.value.PerlValuesManager.computeValue(PerlValuesManager.java:156)
at com.perl5.lang.perl.idea.codeInsight.typeInference.value.PerlValuesManager.lambda$null$0(PerlValuesManager.java:140)
at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:113)
at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
at com.perl5.lang.perl.idea.codeInsight.typeInference.value.PerlValuesManager.lambda$from$1(PerlValuesManager.java:140)
at com.intellij.psi.util.CachedValuesManager.lambda$getCachedValue$0(CachedValuesManager.java:148)
at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:240)
at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:113)
at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
at com.intellij.util.CachedValuesManagerImpl.getCachedValueFromExHolder(CachedValuesManagerImpl.java:72)
at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:45)
at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:147)
at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:129)
at com.perl5.lang.perl.idea.codeInsight.typeInference.value.PerlValuesManager.from(PerlValuesManager.java:138)
at com.intellij.util.containers.ContainerUtilRt.map2List(ContainerUtilRt.java:389)
at com.intellij.util.containers.ContainerUtil.map(ContainerUtil.java:1997)
at com.perl5.lang.perl.psi.mixins.PerlMethodMixin.computePerlValue(PerlMethodMixin.java:73)
at com.perl5.lang.perl.idea.codeInsight.typeInference.value.PerlValuesManager.computeValue(PerlValuesManager.java:156)
at com.perl5.lang.perl.idea.codeInsight.typeInference.value.PerlValuesManager.lambda$null$0(PerlValuesManager.java:140)
at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:113)
at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
at com.perl5.lang.perl.idea.codeInsight.typeInference.value.PerlValuesManager.lambda$from$1(PerlValuesManager.java:140)
at com.intellij.psi.util.CachedValuesManager.lambda$getCachedValue$0(CachedValuesManager.java:148)
at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:240)
at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:113)
at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
at com.intellij.util.CachedValuesManagerImpl.getCachedValueFromExHolder(CachedValuesManagerImpl.java:72)
at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:45)
at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:147)
at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:129)
at com.perl5.lang.perl.idea.codeInsight.typeInference.value.PerlValuesManager.from(PerlValuesManager.java:138)
at com.perl5.lang.perl.idea.codeInsight.typeInference.value.PerlCallValue.from(PerlCallValue.java:352)
at com.perl5.lang.perl.psi.references.PerlSubReference.resolveInner(PerlSubReference.java:46)
at com.intellij.psi.impl.source.resolve.ResolveCache$PolyVariantResolver.resolve(ResolveCache.java:68)
at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$0(ResolveCache.java:149)
at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:113)
at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:148)
at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:179)
at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:171)
at com.perl5.lang.perl.psi.references.PerlCachingReference.multiResolve(PerlCachingReference.java:60)
at com.perl5.lang.perl.psi.utils.PerlResolveUtil.processResolveTargets(PerlResolveUtil.java:155)
at com.perl5.lang.perl.psi.utils.PerlResolveUtil.processResolveTargets(PerlResolveUtil.java:135)
at com.perl5.lang.perl.idea.inspections.PerlDeprecatedInspection$1.visitSubNameElement(PerlDeprecatedInspection.java:41)
at com.perl5.lang.perl.psi.impl.PerlSubNameElementImpl.accept(PerlSubNameElementImpl.java:39)
at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:75)
at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:63)
at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:297)
at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$5(LocalInspectionsPass.java:265)
at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:156)
at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:148)
at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$6(LocalInspectionsPass.java:262)
at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:127)
at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:116)
at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$7(LocalInspectionsPass.java:262)
at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1105)
at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:204)
at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)]
```

**Comment by hurricup** [comment]
The problem is the suspension context. We have only file and line number, and context being mapped to the first non-space element on the line. And it may has no instruction.
The only way I can see here is to make advanced search in the CFG to find the smallest matching covering  instruction.
