### ISSUE TITLE
Unable to find instruction exception (supposedly debugger)

### ISSUE THREAD

**Issue by hurricup** [Camelcade/Perl5-IDEA#2089]
Build: PS-192.5728.108
OS: Mac OS X x86_64 10.14.6
Java Vendor: JetBrains s.r.o
Java Version: 11.0.3
Java Arch: 64 bit
Java Runtime Version: 11.0.3+12-b304.10
Perl Plugin Version: 2019.2
Description: <none>

```
IdeaLoggingEvent[message=null, throwable=java.lang.Throwable: Unable to find an instruction for class com.perl5.lang.perl.psi.impl.PsiPerlScalarVariableImpl; $p; (23662,23664); LightVirtualFile: /xxl_prepro7.pl
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.perl5.lang.perl.psi.utils.PerlResolveUtil.getValueFromControlFlow(PerlResolveUtil.java:260)
	at com.perl5.lang.perl.psi.utils.PerlResolveUtil.inferVariableValue(PerlResolveUtil.java:192)
	at com.perl5.lang.perl.psi.mixins.PerlVariableMixin.computePerlValue(PerlVariableMixin.java:88)
	at com.perl5.lang.perl.idea.codeInsight.typeInference.value.PerlValuesManager.computeValue(PerlValuesManager.java:158)
	at com.perl5.lang.perl.idea.codeInsight.typeInference.value.PerlValuesManager.lambda$null$0(PerlValuesManager.java:142)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
	at com.perl5.lang.perl.idea.codeInsight.typeInference.value.PerlValuesManager.lambda$from$1(PerlValuesManager.java:142)
	at com.intellij.psi.util.CachedValuesManager.lambda$getCachedValue$0(CachedValuesManager.java:148)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:240)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValueFromExHolder(CachedValuesManagerImpl.java:72)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:45)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:147)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:129)
	at com.perl5.lang.perl.idea.codeInsight.typeInference.value.PerlValuesManager.from(PerlValuesManager.java:140)
	at com.perl5.lang.perl.psi.mixins.PerlMethodMixin.computePerlValue(PerlMethodMixin.java:98)
	at com.perl5.lang.perl.idea.codeInsight.typeInference.value.PerlValuesManager.computeValue(PerlValuesManager.java:158)
	at com.perl5.lang.perl.idea.codeInsight.typeInference.value.PerlValuesManager.lambda$null$0(PerlValuesManager.java:142)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
	at com.perl5.lang.perl.idea.codeInsight.typeInference.value.PerlValuesManager.lambda$from$1(PerlValuesManager.java:142)
	at com.intellij.psi.util.CachedValuesManager.lambda$getCachedValue$0(CachedValuesManager.java:148)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:240)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValueFromExHolder(CachedValuesManagerImpl.java:72)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:45)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:147)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:129)
	at com.perl5.lang.perl.idea.codeInsight.typeInference.value.PerlValuesManager.from(PerlValuesManager.java:140)
	at com.perl5.lang.perl.idea.codeInsight.typeInference.value.PerlCallValue.from(PerlCallValue.java:352)
	at com.perl5.lang.perl.psi.references.PerlSubReference.resolveInner(PerlSubReference.java:46)
	at com.intellij.psi.impl.source.resolve.ResolveCache$PolyVariantResolver.resolve(ResolveCache.java:68)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$0(ResolveCache.java:149)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:148)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:179)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:171)
	at com.perl5.lang.perl.psi.references.PerlCachingReference.multiResolve(PerlCachingReference.java:60)
	at com.perl5.lang.perl.idea.annotators.PerlAnnotator.annotate(PerlAnnotator.java:134)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:121)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:351)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:290)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:311)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:70)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:281)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:225)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:429)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:421)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:397)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:204)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:395)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)]
```

**Comment by a1111exe** [comment]
Also got this kind of exceptions. Strange that I can't reproduce this in isolated code. In production code every time I open specific file one of these exceptions (or both) happen:
[Unable to find an instruction for class com.perl5.lang.perl.psi.impl.PsiPerlArrayVariableImpl](https://camelcade.myjetbrains.com/youtrack/issue/CAMELCADE-1752)
[Unable to find an instruction for class com.perl5.lang.perl.psi.impl.PsiPerlScalarVariableImpl](https://camelcade.myjetbrains.com/youtrack/issue/CAMELCADE-1780)

**Comment by hurricup** [comment]
Ye, there are some tricky syntaxes which are not handled properly. They only I've managed to figure out so far - legacy switch/case usages.
In the exceptions messages you should see a fragments of code. Probably you could obfuscate them somehow and post here? This bug is about some specific language constructions. Don't know which :(

**Comment by a1111exe** [comment]
The file is over 2000 lines. No switch/case usages in it. I found those lines with variables mentioned in the exceptions messages, and tried to recreate the code structure in isolated  project - still no luck in reproducing the issue. In general those lines are parts of constant declaration with heredoc string and some interpolated variables in it. It looks like:

```
use constant SOME_SQL => <<SQL;
SELECT
  '<field_token>'                               AS TOKEN,
  field1                                        AS FIELD1,
  field2                                        AS FIELD2,
  IF(field2 IN ($Cfg::cfg_scalar), TRUE, FALSE) AS FIELD2_OK,
  @{[ join ', ', @Cfg::cfg_fields_arr ]}
FROM <table_token>
WHERE <conditions_token>
SQL
```
But again, this piece of code doesn't trigger exceptions when I try it in isolated project...
I'll mess with this some more when I have time, if there will be any luck - I'll post here the details.

**Comment by a1111exe** [comment]
Got it! :)

That's the code:
[camelcade-issues-exception.zip](https://github.com/Camelcade/Perl5-IDEA/files/3457497/camelcade-issues-exception.zip)

It seems, the exceptions are triggered when there is some other **constant with heredoc** defined **above** the constant definition with variables.  The first exception is thrown when I hit enter after `<<MULTI;` above the problematic definition. After that it seems that any messing with the file like editing and saving triggers the exception. Hopefully you'll be able to reproduce this with the attached micro-project.

**Comment by hurricup** [comment]
Thank you very much, your feedback was very helpful!
