### ISSUE TITLE
docker plugin is not working with IDEA 2019.3

### ISSUE THREAD

**Issue by elcamlost** [Camelcade/Perl5-IDEA#2126]
My IDEA info
```
IntelliJ IDEA 2019.3 (Ultimate Edition)
Build #IU-193.5233.102, built on November 28, 2019
Subscription is active until August 23, 2020
Runtime version: 11.0.4+10-b520.11 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.1
GC: ParNew, ConcurrentMarkSweep
```

Docker plugin doesn't work and prevents IDEA to even start.
Logs:

on startup
```
2019-12-02 13:08:25,696 [   9136]   WARN - llij.ide.plugins.PluginManager - Plugin "Docker integration" is incompatible (until build 182.SNAPSHOT < IU-193.5233.102) 
```

and later when I'm trying to open any (including non-perl) projects
```
2019-12-02 13:08:44,265 [  27705]  ERROR - m.PlatformProjectOpenProcessor - Key com.perl5.lang.perl.idea.sdk.host.docker.PerlDockerProjectSettings duplicated 
org.picocontainer.defaults.DuplicateComponentKeyRegistrationException: Key com.perl5.lang.perl.idea.sdk.host.docker.PerlDockerProjectSettings duplicated
	at com.intellij.util.pico.DefaultPicoContainer.registerComponent(DefaultPicoContainer.java:124)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.registerServices(PlatformComponentManagerImpl.kt:234)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.registerComponents(PlatformComponentManagerImpl.kt:101)
	at com.intellij.openapi.project.impl.ProjectImpl.registerComponents(ProjectImpl.java:250)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.initProject(ProjectManagerImpl.java:313)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.convertAndLoadProject(ProjectManagerImpl.java:624)
	at com.intellij.platform.PlatformProjectOpenProcessor.prepareProject(PlatformProjectOpenProcessor.java:315)
	at com.intellij.platform.PlatformProjectOpenProcessor.lambda$openExistingProject$0(PlatformProjectOpenProcessor.java:241)
	at com.intellij.platform.ProjectUiFrameAllocator$run$1$1.run(ProjectFrameAllocator.kt:77)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:247)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:888)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:150)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$4(ApplicationImpl.java:441)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.util.ConcurrencyUtil.lambda$underThreadNameRunnable$3(ConcurrencyUtil.java:209)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by hurricup** [comment]
You may uninstall docker/wsl plugin. It's now integrated into main one and should work as is. Unfortunately there is no way to do it from the plugin's side.

**Comment by elcamlost** [comment]
Yap, this is working. Thanks.
