### ISSUE TITLE
Perl Plugin crashes IntelliJ IDEA 2019.3.2

### ISSUE THREAD

**Issue by mahaag** [Camelcade/Perl5-IDEA#2132]
Downloaded IntelliJ IDEA community edition 2019.3.2 for Linux and extracted the archive on my Xubuntu 18.04.3 LTS (Bionic Beaver).

Start IDE on the command line and do not import any settings to have a fresh install. Then "Skip Remaining and Set Defaults". Install the Perl Plugin via "Configure -> Plugins", search for "perl" and install the Perl Plugin version 2019.3. Do not "Restart IDE", but close the IDE and restart it via command line to see any stack traces.

Click on "Create New Project" and nothing will happen anymore in the IDE. On the command line getting a stack trace:

``
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
2020-01-31 09:19:11,025 [  30055]  ERROR - llij.ide.plugins.PluginManager - null 
java.lang.NullPointerException
        at java.desktop/javax.swing.text.html.StyleSheet.createResolvedStyle(StyleSheet.java:1483)
        at java.desktop/javax.swing.text.html.StyleSheet.createResolvedStyle(StyleSheet.java:1704)
        at java.desktop/javax.swing.text.html.StyleSheet.getResolvedStyle(StyleSheet.java:1330)
        at java.desktop/javax.swing.text.html.StyleSheet.getRule(StyleSheet.java:281)
        at java.desktop/javax.swing.text.html.StyleSheet.createResolvedStyle(StyleSheet.java:1483)
        at java.desktop/javax.swing.text.html.StyleSheet.createResolvedStyle(StyleSheet.java:1562)
        at java.desktop/javax.swing.text.html.StyleSheet.getResolvedStyle(StyleSheet.java:1318)
        at java.desktop/javax.swing.text.html.StyleSheet.getRule(StyleSheet.java:255)
        at java.desktop/javax.swing.text.html.StyleSheet$ViewAttributeSet.<init>(StyleSheet.java:2745)
        at java.desktop/javax.swing.text.html.StyleSheet.getViewAttributes(StyleSheet.java:362)
        at java.desktop/javax.swing.text.html.BlockView.setPropertiesFromAttributes(BlockView.java:404)
        at java.desktop/javax.swing.text.html.BlockView.setParent(BlockView.java:74)
        at java.desktop/javax.swing.text.CompositeView.replace(CompositeView.java:219)
        at java.desktop/javax.swing.text.BoxView.replace(BoxView.java:182)
        at java.desktop/javax.swing.text.CompositeView.loadChildren(CompositeView.java:114)
        at java.desktop/javax.swing.text.CompositeView.setParent(CompositeView.java:139)
        at java.desktop/javax.swing.text.html.BlockView.setParent(BlockView.java:72)
        at java.desktop/javax.swing.plaf.basic.BasicHTML$Renderer.<init>(BasicHTML.java:411)
        at java.desktop/javax.swing.plaf.basic.BasicHTML.createHTMLView(BasicHTML.java:84)
        at java.desktop/javax.swing.plaf.basic.BasicHTML.updateRenderer(BasicHTML.java:231)
        at java.desktop/javax.swing.plaf.basic.BasicLabelUI.propertyChange(BasicLabelUI.java:482)
        at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:341)
        at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:333)
        at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:266)
        at java.desktop/java.awt.Component.firePropertyChange(Component.java:8747)
        at java.desktop/javax.swing.JLabel.setText(JLabel.java:324)
        at com.intellij.ide.util.newProjectWizard.AddSupportForFrameworksPanel.$$$loadLabelText$$$(AddSupportForFrameworksPanel.java)
        at com.intellij.ide.util.newProjectWizard.AddSupportForFrameworksPanel.$$$setupUI$$$(AddSupportForFrameworksPanel.java)
        at com.intellij.ide.util.newProjectWizard.AddSupportForFrameworksPanel.<init>(AddSupportForFrameworksPanel.java:67)
        at com.intellij.ide.projectWizard.ProjectTypeStep.<init>(ProjectTypeStep.java:168)
        at com.intellij.ide.projectWizard.NewProjectWizard.init(NewProjectWizard.java:51)
        at com.intellij.ide.projectWizard.NewProjectWizard.<init>(NewProjectWizard.java:40)
        at com.intellij.ide.actions.NewProjectAction.actionPerformed(NewProjectAction.java:26)
        at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:298)
        at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:83)
        at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:149)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:313)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.invokeAction(ActionUtil.java:474)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.invokeAction(ActionUtil.java:459)
        at com.intellij.ui.components.labels.ActionLink$1.linkSelected(ActionLink.java:45)
        at com.intellij.ui.components.labels.LinkLabel.doClick(LinkLabel.java:142)
        at com.intellij.ui.components.labels.ActionLink.doClick(ActionLink.java:54)
        at com.intellij.ui.components.labels.LinkLabel$MyMouseHandler.mouseReleased(LinkLabel.java:330)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6651)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
        at java.desktop/java.awt.Component.processEvent(Component.java:6416)
        at java.desktop/java.awt.Container.processEvent(Container.java:2263)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:908)
        at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:846)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:778)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:424)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2020-01-31 09:19:11,026 [  30056]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 2019.3.2  Build #IC-193.6015.39 
2020-01-31 09:19:11,027 [  30057]  ERROR - llij.ide.plugins.PluginManager - JDK: 11.0.5; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2020-01-31 09:19:11,027 [  30057]  ERROR - llij.ide.plugins.PluginManager - OS: Linux 
2020-01-31 09:19:11,030 [  30060]  ERROR - llij.ide.plugins.PluginManager - Last Action: WelcomeScreen.CreateNewProject 
``

If I don't use the bundled JRE, I don't get this exception. If I don't install the Perl Plugin everything is fine, too.

Then downloaded IntelliJ IDEA 2019.2.4 and installed the Perl Plugin. Here is everything working as expected.

**Comment by hurricup** [comment]
This is IDE's problem, not plugins. Please, follow the https://youtrack.jetbrains.com/issue/IDEA-230068
