### ISSUE TITLE
IOOBE in formatter

### ISSUE THREAD

**Issue by hurricup** [Camelcade/Perl5-IDEA#2351]
Something fishy is going on with line numbering. Uncommited document?

```
Build: IU-203.5981.155
OS: Mac OS X x86_64 10.15.7
Java Vendor: JetBrains s.r.o.
Java Version: 11.0.9
Java Arch: 64 bit
Java Runtime Version: 11.0.9+11-b1145.21
Perl Plugin Version: 203.5784.10-EAP-SNAPSHOT
Description: <none>
Message: none
Throwable:
java.lang.IndexOutOfBoundsException: Wrong offset: 62836. Should be in range: [0, 61572]
	at com.intellij.openapi.editor.impl.LineSet.findLineIndex(LineSet.java:165)
	at com.intellij.openapi.editor.impl.DocumentImpl.getLineNumber(DocumentImpl.java:1001)
	at com.perl5.lang.perl.idea.folding.PerlFoldingBuilderBase.addDescriptorFor(PerlFoldingBuilderBase.java:53)
	at com.perl5.lang.perl.idea.folding.PerlFoldingBuilder$FoldingRegionsCollector.visitBlock(PerlFoldingBuilder.java:387)
	at com.perl5.lang.perl.psi.impl.PsiPerlBlockImpl.accept(PsiPerlBlockImpl.java:20)
	at com.perl5.lang.perl.psi.impl.PsiPerlBlockImpl.accept(PsiPerlBlockImpl.java:24)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.perl5.lang.perl.psi.PerlRecursiveVisitor.visitElement(PerlRecursiveVisitor.java:43)
	at com.perl5.lang.perl.idea.folding.PerlFoldingBuilder$FoldingRegionsCollector.visitElement(PerlFoldingBuilder.java:349)
	at com.perl5.lang.perl.psi.PerlVisitor.visitPerlSubElement(PerlVisitor.java:165)
	at com.perl5.lang.perl.psi.PerlVisitor.visitPerlSubDefinitionElement(PerlVisitor.java:161)
	at com.perl5.lang.perl.psi.PerlVisitor.visitSubDefinition(PerlVisitor.java:156)
	at com.perl5.lang.perl.psi.impl.PsiPerlSubDefinitionImpl.accept(PsiPerlSubDefinitionImpl.java:27)
	at com.perl5.lang.perl.psi.impl.PsiPerlSubDefinitionImpl.accept(PsiPerlSubDefinitionImpl.java:31)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.perl5.lang.perl.psi.PerlRecursiveVisitor.visitElement(PerlRecursiveVisitor.java:43)
	at com.perl5.lang.perl.idea.folding.PerlFoldingBuilder$FoldingRegionsCollector.visitElement(PerlFoldingBuilder.java:349)
	at com.perl5.lang.perl.psi.PsiPerlVisitor.visitPerlStatementsContainer(PsiPerlVisitor.java:981)
	at com.perl5.lang.perl.psi.PsiPerlVisitor.visitNamespaceContent(PsiPerlVisitor.java:551)
	at com.perl5.lang.perl.psi.impl.PsiPerlNamespaceContentImpl.accept(PsiPerlNamespaceContentImpl.java:20)
	at com.perl5.lang.perl.psi.impl.PsiPerlNamespaceContentImpl.accept(PsiPerlNamespaceContentImpl.java:24)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.perl5.lang.perl.psi.PerlRecursiveVisitor.visitElement(PerlRecursiveVisitor.java:43)
	at com.perl5.lang.perl.idea.folding.PerlFoldingBuilder$FoldingRegionsCollector.visitElement(PerlFoldingBuilder.java:349)
	at com.perl5.lang.perl.psi.PerlVisitor.visitNamespaceDefinitionElement(PerlVisitor.java:32)
	at com.perl5.lang.perl.psi.PerlVisitor.visitPerlNamespaceDefinitionWithIdentifier(PerlVisitor.java:37)
	at com.perl5.lang.perl.psi.PsiPerlVisitor.visitNamespaceDefinition(PsiPerlVisitor.java:555)
	at com.perl5.lang.perl.psi.impl.PsiPerlNamespaceDefinitionImpl.accept(PsiPerlNamespaceDefinitionImpl.java:27)
	at com.perl5.lang.perl.psi.impl.PsiPerlNamespaceDefinitionImpl.accept(PsiPerlNamespaceDefinitionImpl.java:31)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:185)
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:754)
	at com.perl5.lang.perl.psi.PerlRecursiveVisitor.visitElement(PerlRecursiveVisitor.java:43)
	at com.perl5.lang.perl.idea.folding.PerlFoldingBuilder$FoldingRegionsCollector.visitElement(PerlFoldingBuilder.java:349)
	at com.intellij.psi.PsiElementVisitor.visitFile(PsiElementVisitor.java:35)
	at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:60)
	at com.perl5.lang.perl.idea.folding.PerlFoldingBuilder.buildFoldRegions(PerlFoldingBuilder.java:64)
	at com.intellij.lang.folding.LanguageFolding.buildFoldingDescriptorsNoPlaceholderCaching(LanguageFolding.java:92)
	at com.intellij.lang.folding.LanguageFolding.buildFoldingDescriptors(LanguageFolding.java:75)
	at com.intellij.codeInsight.folding.impl.DocumentFoldingInfo.buildRanges(DocumentFoldingInfo.java:139)
	at com.intellij.codeInsight.folding.impl.DocumentFoldingInfo.setToEditor(DocumentFoldingInfo.java:101)
	at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.restoreFoldingState(CodeFoldingManagerImpl.java:238)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorProvider.lambda$setStateImpl$0(PsiAwareTextEditorProvider.java:111)
	at com.intellij.openapi.editor.impl.FoldingModelImpl.runBatchFoldingOperation(FoldingModelImpl.java:207)
	at com.intellij.openapi.editor.impl.FoldingModelImpl.runBatchFoldingOperation(FoldingModelImpl.java:182)
	at com.intellij.openapi.editor.FoldingModel.runBatchFoldingOperation(FoldingModel.java:107)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorProvider.setStateImpl(PsiAwareTextEditorProvider.java:110)
	at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader.setEditorState(AsyncEditorLoader.java:228)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorImpl.setState(TextEditorImpl.java:160)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.restoreEditorState(FileEditorManagerImpl.java:1039)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4Edt(FileEditorManagerImpl.java:924)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl4$17(FileEditorManagerImpl.java:857)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.runBulkTabChange(FileEditorManagerImpl.java:1677)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl4$18(FileEditorManagerImpl.java:856)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:463)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:481)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4(FileEditorManagerImpl.java:855)
	at com.intellij.openapi.fileEditor.impl.EditorWindow.split(EditorWindow.java:630)
	at com.intellij.openapi.fileEditor.impl.DockableEditorTabbedContainer.add(DockableEditorTabbedContainer.java:149)
	at com.intellij.ui.docking.impl.DockManagerImpl$MyDragSession.process(DockManagerImpl.java:321)
	at com.intellij.openapi.fileEditor.impl.EditorTabbedContainer$MyDragOutDelegate.dragOutFinished(EditorTabbedContainer.java:500)
	at com.intellij.ui.tabs.impl.DragHelper.processDragOutFinish(DragHelper.java:74)
	at com.intellij.ui.MouseDragHelper.mouseReleased(MouseDragHelper.java:158)
	at com.intellij.openapi.wm.impl.IdeGlassPaneImpl.fireMouseEvent(IdeGlassPaneImpl.java:434)
	at com.intellij.openapi.wm.impl.IdeGlassPaneImpl.preprocess(IdeGlassPaneImpl.java:297)
	at com.intellij.openapi.wm.impl.IdeGlassPaneImpl.dispatchMouseEvent(IdeGlassPaneImpl.java:114)
	at com.intellij.openapi.wm.impl.IdeGlassPaneImpl.dispatch(IdeGlassPaneImpl.java:90)
	at com.intellij.ide.IdeEventQueue.dispatchByCustomDispatchers(IdeEventQueue.java:934)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:507)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
https://camelcade.myjetbrains.com/youtrack/issue/CAMELCADE-226

**Comment by hurricup** [comment]
Seems obsolete, no recent reports

**Comment by hurricup** [comment]
Folding builder also affected #2538
