### ISSUE TITLE
Should be called at least in the state COMPONENTS_LOADED, the current state is: CONFIGURATION_STORE_INITIALIZED

### ISSUE THREAD

**Issue by hurricup** [Camelcade/Perl5-IDEA#2445]
https://camelcade.myjetbrains.com/youtrack/issue/CAMELCADE-2064

```
Build: WS-213.5744.224
OS: Mac OS X x86_64 11.5.2
Java Vendor: JetBrains s.r.o.
Java Version: 11.0.13
Java Runtime Version: 11.0.13+7-b1751.19
Perl Plugin Version: 2021.3
Description: <none>
Message: Should be called at least in the state COMPONENTS_LOADED, the current state is: CONFIGURATION_STORE_INITIALIZED
Current violators count: 1
Throwable:
java.lang.Throwable
	at com.intellij.diagnostic.LoadingState.logStateError(LoadingState.java:52)
	at com.intellij.diagnostic.LoadingState.checkOccurred(LoadingState.java:48)
	at com.intellij.psi.tree.IElementType.<init>(IElementType.java:101)
	at com.perl5.lang.perl.parser.elementTypes.PerlTokenType.<init>(PerlTokenType.java:32)
	at com.perl5.lang.perl.parser.elementTypes.PerlTokenType.<init>(PerlTokenType.java:28)
	at com.perl5.lang.perl.parser.elementTypes.PerlElementType.<init>(PerlElementType.java:25)
	at com.perl5.lang.perl.parser.elementTypes.PerlElementTypeEx.<init>(PerlElementTypeEx.java:38)
	at com.perl5.lang.perl.parser.elementTypes.PerlElementTypeFactory.getElementType(PerlElementTypeFactory.java:122)
	at com.perl5.lang.perl.lexer.PerlElementTypesGenerated.<clinit>(PerlElementTypesGenerated.java:12)
	at com.perl5.lang.perl.idea.editor.smartkeys.PerlTypedHandler.<clinit>(PerlTypedHandler.java:59)
	at java.base/jdk.internal.misc.Unsafe.allocateInstance(Native Method)
	at java.base/java.lang.invoke.DirectMethodHandle.allocateInstance(DirectMethodHandle.java:482)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:830)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.instantiateClass(XmlExtensionAdapter.java:99)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter$SimpleConstructorInjectionAdapter.instantiateClass(XmlExtensionAdapter.java:116)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.java:66)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.java:489)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:437)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.computeExtensionList(ExtensionPointImpl.java:249)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensionList(ExtensionPointImpl.java:243)
	at com.intellij.openapi.extensions.ExtensionPoint.hasExtension(ExtensionPoint.java:79)
	at io.senya.intellij.components.SenyaPluginLifecycleManager.unregisterExtensions(SenyaPluginLifecycleManager.java:222)
	at io.senya.intellij.components.SenyaPluginLifecycleManager.deactivate(SenyaPluginLifecycleManager.java:138)
	at io.senya.intellij.components.SenyaPluginLifecycleManager.<init>(SenyaPluginLifecycleManager.java:92)
	at io.senya.intellij.components.SenyaPluginLifecycleManager$SenyaPluginLifecycleManagerHelper.<clinit>(SenyaPluginLifecycleManager.java:49)
	at io.senya.intellij.components.SenyaPluginLifecycleManager.getInstance(SenyaPluginLifecycleManager.java:54)
	at io.senya.intellij.components.SenyaPluginComponent.initComponent(SenyaPluginComponent.java:29)
	at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:44)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:113)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:67)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:60)
	at com.intellij.serviceContainer.ComponentManagerImpl.createComponents(ComponentManagerImpl.kt:401)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$loadComponents$5(ApplicationImpl.java:370)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.application.impl.ApplicationImpl.loadComponents(ApplicationImpl.java:370)
	at com.intellij.idea.ApplicationLoader$startApp$loadComponentInEdtFuture$1.run(ApplicationLoader.kt:141)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:348)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:131)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:187)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:407)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by hurricup** [comment]
Seems obsolete, no recent reports
