### ISSUE TITLE
Unable to view variable values when remote debugging from a remote IDE

### ISSUE THREAD

**Issue by markAtAthena** [Camelcade/Perl5-IDEA#2477]
When I try a remote Perl debugging session on a remote IDE (IntellIJ via Gateway), it now does connect properly in the latest EAP but it can't view variable values:

<img width="773" alt="image" src="https://user-images.githubusercontent.com/52248411/159299565-f0e2a062-8e16-4a38-a074-45469fb7f923.png">

<img width="448" alt="image" src="https://user-images.githubusercontent.com/52248411/159299643-86bbc16f-c840-44a7-9fab-cca4b887e377.png">

ideaIU-221.5080.9

 The only thing I see in the log is:
 
 2022-03-21 11:49:01,159 [1511624] SEVERE - #c.i.d.PluginException - 'XCompositeNode#tooManyChildren(int)' is deprecated and going to be removed soon. Use #tooManyChildren(Int, Runnable) instead
java.lang.Throwable: 'XCompositeNode#tooManyChildren(int)' is deprecated and going to be removed soon. Use #tooManyChildren(Int, Runnable) instead
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:105)
	at com.jetbrains.rdserver.debugger.CodeWithMeCompositeNodeBase.tooManyChildren(CodeWithMeCompositeNode.kt:68)
	at com.perl5.lang.perl.debugger.PerlDebugUtil$1.run(PerlDebugUtil.java:102)
	at com.perl5.lang.perl.debugger.protocol.PerlDebuggingEventsDeserializer.deserialize(PerlDebuggingEventsDeserializer.java:82)
	at com.perl5.lang.perl.debugger.protocol.PerlDebuggingEventsDeserializer.deserialize(PerlDebuggingEventsDeserializer.java:29)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:963)
	at com.google.gson.Gson.fromJson(Gson.java:928)
	at com.google.gson.Gson.fromJson(Gson.java:877)
	at com.google.gson.Gson.fromJson(Gson.java:848)
	at com.perl5.lang.perl.debugger.PerlDebugThread.processResponse(PerlDebugThread.java:248)
	at com.perl5.lang.perl.debugger.PerlDebugThread.doRun(PerlDebugThread.java:213)
	at com.perl5.lang.perl.debugger.PerlDebugThread.run(PerlDebugThread.java:225)
2022-03-21 11:49:01,160 [1511625] SEVERE - #c.i.d.PluginException - IntelliJ IDEA 2022.1 EAP  Build #IU-221.5080.9
2022-03-21 11:49:01,160 [1511625] SEVERE - #c.i.d.PluginException - JDK: 11.0.14.1; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2022-03-21 11:49:01,160 [1511625] SEVERE - #c.i.d.PluginException - OS: Linux
2022-03-21 11:49:01,161 [1511626] SEVERE - #c.i.d.PluginException - Plugin to blame: Perl version: 221.4165.146-EAP-SNAPSHOT
2022-03-21 11:49:04,725 [1515190]   INFO - #c.i.c.ComponentStoreImpl - Saving appHttpConfigurable took 22 ms, PerlInterpreters took 31 ms

**Comment by hurricup** [comment]
If this problem is still actual, I need step by step reproduction. Because I'm not familiar with gateway at all and need to know exactly what are you doing.

**Comment by hurricup** [comment]
Feel free to re-open if will be able to provide additional information.
