### ISSUE TITLE
Unable to update to 2022.1

### ISSUE THREAD

**Issue by targzeta** [Camelcade/Perl5-IDEA#2496]
Hi,
I have updated PyCharm (but also IntellijIdea) to the latest version. The new version of the plugin (2022.1) has been installed. At start time I have this error and the plugins is disabled.
![screenshot_20220513_120503](https://user-images.githubusercontent.com/2431105/168264572-6abf48ea-3195-474c-966a-db35e7f901cf.jpg)

Best regards,
Emanuele

**Comment by hurricup** [comment]
Could you please provide ide information (available from help menu) and copy-paste this stacktrace. Screenshot is hard to process for investigation.

**Comment by targzeta** [comment]
Hi,
thank you for your fast reply!
![screenshot_20220513_125830](https://user-images.githubusercontent.com/2431105/168270537-06beb9e0-5228-4f01-9b6b-868b10fc61b0.jpg)

```
com.intellij.diagnostic.PluginException: Cannot get state after load [Plugin: com.perl5]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:83)
	at com.intellij.diagnostic.PluginException.logPluginError(PluginException.java:100)
	at com.intellij.configurationStore.StateGetterImpl.archiveState(StorageBaseEx.kt:72)
	at com.intellij.configurationStore.ComponentStoreImpl.doInitComponent(ComponentStoreImpl.kt:442)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:373)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:119)
	at com.intellij.configurationStore.ComponentStoreWithExtraComponents.initComponent(ComponentStoreWithExtraComponents.kt:48)
	at com.intellij.serviceContainer.ComponentManagerImpl.initializeComponent$intellij_platform_serviceContainer(ComponentManagerImpl.kt:536)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:55)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:41)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:119)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:73)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:66)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:610)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:584)
	at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
	at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
	at com.intellij.openapi.projectRoots.impl.PerlSdkTable.getInstance(PerlSdkTable.java:171)
	at com.perl5.lang.perl.idea.project.PerlProjectManager.lambda$resetProjectCaches$3(PerlProjectManager.java:141)
	at com.intellij.openapi.util.AtomicNullableLazyValue$1.compute(AtomicNullableLazyValue.java:52)
	at com.intellij.openapi.util.AtomicNullableLazyValue.getValue(AtomicNullableLazyValue.java:30)
	at com.perl5.lang.perl.idea.project.PerlProjectManager.getProjectSdk(PerlProjectManager.java:211)
	at com.perl5.lang.perl.idea.project.PerlProjectManager.lambda$resetProjectCaches$5(PerlProjectManager.java:155)
	at com.intellij.openapi.util.AtomicNotNullLazyValue.lambda$createValue$0(AtomicNotNullLazyValue.java:45)
	at com.intellij.openapi.util.NotNullLazyValue$2.compute(NotNullLazyValue.java:70)
	at com.intellij.openapi.util.AtomicNotNullLazyValue.getValue(AtomicNotNullLazyValue.java:28)
	at com.perl5.lang.perl.idea.project.PerlProjectManager.getProjectSdkLibraryRoots(PerlProjectManager.java:205)
	at com.perl5.lang.perl.idea.project.PerlProjectManager.lambda$resetProjectCaches$6(PerlProjectManager.java:163)
	at com.intellij.openapi.util.AtomicNotNullLazyValue.lambda$createValue$0(AtomicNotNullLazyValue.java:45)
	at com.intellij.openapi.util.NotNullLazyValue$2.compute(NotNullLazyValue.java:70)
	at com.intellij.openapi.util.AtomicNotNullLazyValue.getValue(AtomicNotNullLazyValue.java:28)
	at com.perl5.lang.perl.idea.project.PerlProjectManager.getAllLibraryRoots(PerlProjectManager.java:201)
	at com.perl5.lang.perl.idea.configuration.settings.sdk.PerlLibraryProvider.getRootsToWatch(PerlLibraryProvider.java:41)
	at com.intellij.openapi.roots.impl.ProjectRootManagerComponent.collectWatchRoots(ProjectRootManagerComponent.java:229)
	at com.intellij.openapi.roots.impl.ProjectRootManagerComponent.lambda$addRootsToWatch$5(ProjectRootManagerComponent.java:178)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:933)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:68)
	at com.intellij.openapi.roots.impl.ProjectRootManagerComponent.lambda$addRootsToWatch$7(ProjectRootManagerComponent.java:178)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:241)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:214)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:203)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassCastException: class com.perl5.lang.perl.idea.sdk.PerlSdkAdditionalData$UnknownSdkAdditionalData cannot be cast to class com.perl5.lang.perl.idea.sdk.PerlSdkAdditionalData (com.perl5.lang.perl.idea.sdk.PerlSdkAdditionalData$UnknownSdkAdditionalData and com.perl5.lang.perl.idea.sdk.PerlSdkAdditionalData are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @235834f2)
	at com.perl5.lang.perl.idea.sdk.PerlSdkType.saveAdditionalData(PerlSdkType.java:73)
	at com.intellij.openapi.projectRoots.impl.ProjectJdkImpl.writeExternal(ProjectJdkImpl.java:230)
	at com.intellij.openapi.projectRoots.impl.PerlSdkTable.getState(PerlSdkTable.java:75)
	at com.intellij.openapi.projectRoots.impl.PerlSdkTable.getState(PerlSdkTable.java:43)
	at com.intellij.configurationStore.StateGetterImpl.archiveState(StorageBaseEx.kt:66)
	... 49 more
```

Emanuele

**Comment by hurricup** [comment]
As workaround, could you please locate `PerlInterpreters.xml` file and rename/move it. Should help, but you'll need to re-add perl interpreters in IDE.
Also would be nice to see this file if possible.

**Comment by hurricup** [comment]
f3e2db624c88c96016f6bd72ab00da65ee456116

**Comment by targzeta** [comment]
I'm unable to find that file. I have only found:
`./.local/share/JetBrains/PyCharm2022.1/plugin/lib/com/perl5/lang/perl/idea/editor/notification/PerlInterpreterEditorNotification.class`

I saw your patch. I can wait for the next release without problems ;)!

Thank you,
Emanuele

**Comment by hurricup** [comment]
Artifact should be available here after passing the build: https://github.com/Camelcade/Perl5-IDEA/actions/runs/2319999492
