### ISSUE TITLE
IOOBE on building folding regions

### ISSUE THREAD

**Issue by hurricup** [Camelcade/Perl5-IDEA#2538]
https://camelcade.myjetbrains.com/youtrack/issue/CAMELCADE-8791/java.lang.IndexOutOfBoundsException-Wrong-offset-22640.-Should-be-in-range-0

Presumably - uncommited document.

Build: IU-223.7571.182
OS: Windows 11 amd64 10.0
Java Vendor: JetBrains s.r.o.
Java Version: 17.0.5
Java Runtime Version: 17.0.5+1-b653.14
Perl Plugin Version: 2022.3
Description: <none>
Message: none
```
java.lang.IndexOutOfBoundsException: Wrong offset: 22640. Should be in range: [0, 17796]
	at com.intellij.openapi.editor.impl.LineSet.findLineIndex(LineSet.java:166)
	at com.intellij.openapi.editor.impl.DocumentImpl.getLineNumber(DocumentImpl.java:1015)
	at com.perl5.lang.perl.idea.folding.PerlFoldingBuilderBase.addDescriptorFor(PerlFoldingBuilderBase.java:53)
	at com.perl5.lang.perl.idea.folding.PerlFoldingBuilder$FoldingRegionsCollector.visitBlock(PerlFoldingBuilder.java:387)
	at com.perl5.lang.perl.psi.impl.PsiPerlBlockImpl.accept(PsiPerlBlockImpl.java:20)
	at com.perl5.lang.perl.psi.impl.PsiPerlBlockImpl.accept(PsiPerlBlockImpl.java:25)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:58)
	at com.perl5.lang.perl.psi.PerlRecursiveVisitor.visitElement(PerlRecursiveVisitor.java:43)
	at com.perl5.lang.perl.idea.folding.PerlFoldingBuilder$FoldingRegionsCollector.visitElement(PerlFoldingBuilder.java:349)
	at com.perl5.lang.perl.psi.PerlVisitor.visitPerlSubElement(PerlVisitor.java:165)
	at com.perl5.lang.perl.psi.PerlVisitor.visitPerlSubDefinitionElement(PerlVisitor.java:161)
	at com.perl5.lang.perl.psi.PerlVisitor.visitSubDefinition(PerlVisitor.java:156)
	at com.perl5.lang.perl.psi.impl.PsiPerlSubDefinitionImpl.accept(PsiPerlSubDefinitionImpl.java:27)
	at com.perl5.lang.perl.psi.impl.PsiPerlSubDefinitionImpl.accept(PsiPerlSubDefinitionImpl.java:32)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:58)
	at com.perl5.lang.perl.psi.PerlRecursiveVisitor.visitElement(PerlRecursiveVisitor.java:43)
	at com.perl5.lang.perl.idea.folding.PerlFoldingBuilder$FoldingRegionsCollector.visitElement(PerlFoldingBuilder.java:349)
	at com.perl5.lang.perl.psi.PsiPerlVisitor.visitPerlStatementsContainer(PsiPerlVisitor.java:1014)
	at com.perl5.lang.perl.psi.PsiPerlVisitor.visitNamespaceContent(PsiPerlVisitor.java:556)
	at com.perl5.lang.perl.psi.impl.PsiPerlNamespaceContentImpl.accept(PsiPerlNamespaceContentImpl.java:20)
	at com.perl5.lang.perl.psi.impl.PsiPerlNamespaceContentImpl.accept(PsiPerlNamespaceContentImpl.java:25)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:58)
	at com.perl5.lang.perl.psi.PerlRecursiveVisitor.visitElement(PerlRecursiveVisitor.java:43)
	at com.perl5.lang.perl.idea.folding.PerlFoldingBuilder$FoldingRegionsCollector.visitElement(PerlFoldingBuilder.java:349)
	at com.perl5.lang.perl.psi.PerlVisitor.visitNamespaceDefinitionElement(PerlVisitor.java:32)
	at com.perl5.lang.perl.psi.PerlVisitor.visitPerlNamespaceDefinitionWithIdentifier(PerlVisitor.java:37)
	at com.perl5.lang.perl.psi.PsiPerlVisitor.visitNamespaceDefinition(PsiPerlVisitor.java:560)
	at com.perl5.lang.perl.psi.impl.PsiPerlNamespaceDefinitionImpl.accept(PsiPerlNamespaceDefinitionImpl.java:27)
	at com.perl5.lang.perl.psi.impl.PsiPerlNamespaceDefinitionImpl.accept(PsiPerlNamespaceDefinitionImpl.java:32)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:185)
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:754)
	at com.perl5.lang.perl.psi.PerlRecursiveVisitor.visitElement(PerlRecursiveVisitor.java:43)
	at com.perl5.lang.perl.idea.folding.PerlFoldingBuilder$FoldingRegionsCollector.visitElement(PerlFoldingBuilder.java:349)
	at com.intellij.psi.PsiElementVisitor.visitFile(PsiElementVisitor.java:51)
	at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:60)
	at com.perl5.lang.perl.idea.folding.PerlFoldingBuilder.buildFoldRegions(PerlFoldingBuilder.java:64)
	at com.intellij.lang.folding.LanguageFolding.buildFoldingDescriptorsNoPlaceholderCaching(LanguageFolding.java:89)
	at com.intellij.lang.folding.LanguageFolding.buildFoldingDescriptors(LanguageFolding.java:72)
	at com.intellij.codeInsight.folding.impl.DocumentFoldingInfo.buildRanges(DocumentFoldingInfo.java:139)
	at com.intellij.codeInsight.folding.impl.DocumentFoldingInfo.setToEditor(DocumentFoldingInfo.java:101)
	at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.restoreFoldingState(CodeFoldingManagerImpl.java:243)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorProvider.lambda$setStateImpl$0(PsiAwareTextEditorProvider.java:110)
	at com.intellij.openapi.editor.impl.FoldingModelImpl.runBatchFoldingOperation(FoldingModelImpl.java:281)
	at com.intellij.openapi.editor.impl.FoldingModelImpl.runBatchFoldingOperation(FoldingModelImpl.java:222)
	at com.intellij.openapi.editor.FoldingModel.runBatchFoldingOperation(FoldingModel.java:96)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorProvider.setStateImpl(PsiAwareTextEditorProvider.java:109)
	at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader.setEditorState(AsyncEditorLoader.kt:214)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorImpl.setState(TextEditorImpl.java:163)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.restoreEditorState(FileEditorManagerImpl.java:1239)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4Edt(FileEditorManagerImpl.java:1082)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl4$18(FileEditorManagerImpl.java:1036)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.runBulkTabChange(FileEditorManagerImpl.java:1894)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl4$19(FileEditorManagerImpl.java:1035)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:408)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:441)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4(FileEditorManagerImpl.java:1030)
	at com.intellij.openapi.fileEditor.impl.EditorWindow.split(EditorWindow.kt:392)
	at com.intellij.openapi.fileEditor.impl.DockableEditorTabbedContainer.add(DockableEditorTabbedContainer.java:147)
	at com.intellij.ui.docking.impl.DockManagerImpl$MyDragSession.process(DockManagerImpl.java:354)
	at com.intellij.openapi.fileEditor.impl.EditorTabbedContainer$MyDragOutDelegate.dragOutFinished(EditorTabbedContainer.java:521)
	at com.intellij.ui.tabs.impl.DragHelper.processDragOutFinish(DragHelper.java:78)
	at com.intellij.ui.MouseDragHelper.mouseReleased(MouseDragHelper.java:160)
	at com.intellij.openapi.wm.impl.IdeGlassPaneImpl.fireMouseEvent(IdeGlassPaneImpl.java:428)
	at com.intellij.openapi.wm.impl.IdeGlassPaneImpl.preprocess(IdeGlassPaneImpl.java:291)
	at com.intellij.openapi.wm.impl.IdeGlassPaneImpl.dispatchMouseEvent(IdeGlassPaneImpl.java:115)
	at com.intellij.openapi.wm.impl.IdeGlassPaneImpl.dispatch(IdeGlassPaneImpl.java:91)
	at com.intellij.ide.IdeEventQueue.dispatchByCustomDispatchers(IdeEventQueue.java:854)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:731)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:774)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by hurricup** [comment]
https://youtrack.jetbrains.com/issue/IDEA-308219/IOOBE-in-folding-builder-after-splitting-dragging

**Comment by Ashark** [comment]
Links are 404

**Comment by hurricup** [comment]
Yes, issues may contain sensitive information, so the are not publicly available
