### ISSUE TITLE
Actions erroring while used with WSL sdk

### ISSUE THREAD

**Issue by hurricup** [Camelcade/Perl5-IDEA#2539]
- https://camelcade.myjetbrains.com/youtrack/issue/CAMELCADE-8713/
- https://youtrack.jetbrains.com/issue/IDEA-308110

There is an issue with obtaining `mntPoint` under progress.

Build: IU-221.5080.210
OS: Windows 10 amd64 10.0
Java Vendor: JetBrains s.r.o.
Java Version: 11.0.14.1
Java Runtime Version: 11.0.14.1+1-b2043.25
Perl Plugin Version: 2022.1
Description: <none>
Message: none
```
java.lang.Throwable: AWT events are prohibited inside MojoGenerateAppAction#update (com.perl5.lang.mojolicious.idea.actions.MojoGenerateAppAction); got java.awt.event.ComponentEvent[COMPONENT_RESIZED (224,4 16x16)] on javax.swing.JLabel[,224,4,16x16,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=8388608,maximumSize=,minimumSize=,preferredSize=,defaultIcon=com.intellij.ui.AnimatedIcon$Default@2bda3fed,disabledIcon=,horizontalAlignment=CENTER,horizontalTextPosition=TRAILING,iconTextGap=4,labelFor=,text=,verticalAlignment=CENTER,verticalTextPosition=CENTER]
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.ide.ProhibitAWTEvents.dispatch(ProhibitAWTEvents.java:40)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:460)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at com.intellij.ide.IdeEventQueue.pumpEventsForHierarchy(IdeEventQueue.java:943)
	at com.intellij.openapi.progress.util.ProgressWindow.lambda$startBlocking$4(ProgressWindow.java:205)
	at com.intellij.openapi.application.impl.ApplicationImpl.runUnlockingIntendedWrite(ApplicationImpl.java:899)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:201)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$execFromEDT$6(ProgressRunner.java:321)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:753)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731)
	at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108)
	at com.intellij.openapi.progress.impl.ProgressRunner.execFromEDT(ProgressRunner.java:318)
	at com.intellij.openapi.progress.impl.ProgressRunner.submit(ProgressRunner.java:259)
	at com.intellij.openapi.progress.impl.ProgressRunner.submitAndGet(ProgressRunner.java:185)
	at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:477)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:385)
	at com.intellij.openapi.progress.ProgressManager.run(ProgressManager.java:191)
	at com.intellij.execution.wsl.WslDistributionDescriptor.executeOrRunTask(WslDistributionDescriptor.java:198)
	at com.intellij.execution.wsl.WslDistributionDescriptor.lambda$new$1(WslDistributionDescriptor.java:50)
	at com.intellij.execution.wsl.WslDistributionDescriptor$2.compute(WslDistributionDescriptor.java:212)
	at com.intellij.openapi.util.ClearableLazyValue.getValue(ClearableLazyValue.java:39)
	at com.intellij.execution.wsl.WslDistributionDescriptor$2.getValue(WslDistributionDescriptor.java:222)
	at com.intellij.execution.wsl.WslDistributionDescriptor.getMntRoot(WslDistributionDescriptor.java:128)
	at com.intellij.execution.wsl.WSLDistribution.getMntRoot(WSLDistribution.java:527)
	at com.intellij.execution.wsl.WSLDistribution.getWslPath(WSLDistribution.java:518)
	at com.perl5.lang.perl.idea.sdk.host.wsl.PerlWslData.getHelpersRootPath(PerlWslData.java:102)
	at com.perl5.lang.perl.idea.sdk.host.PerlHostData.getLocalPath(PerlHostData.java:157)
	at com.perl5.lang.perl.idea.sdk.host.PerlHostData.getLocalPath(PerlHostData.java:180)
	at com.perl5.lang.perl.util.PerlRunUtil.getBinDirectories(PerlRunUtil.java:347)
	at com.perl5.lang.perl.util.PerlRunUtil.findScript(PerlRunUtil.java:318)
	at com.perl5.lang.mojolicious.MojoUtil.getMojoScript(MojoUtil.java:45)
	at com.perl5.lang.mojolicious.MojoUtil.getMojoScript(MojoUtil.java:53)
	at com.perl5.lang.mojolicious.MojoUtil.isMojoAvailable(MojoUtil.java:77)
	at com.perl5.lang.mojolicious.idea.actions.MojoScriptAction.isEnabled(MojoScriptAction.java:42)
	at com.perl5.lang.mojolicious.idea.actions.MojoGenerateAction.isEnabled(MojoGenerateAction.java:63)
	at com.perl5.lang.perl.idea.actions.PerlActionBase.update(PerlActionBase.java:59)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performDumbAwareUpdate$0(ActionUtil.java:131)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:145)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doUpdate(ActionUpdater.java:639)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$updateActionReal$4(ActionUpdater.java:125)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$computeOnEdt$6(ActionUpdater.java:209)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:58)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:58)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$computeOnEdt$7(ActionUpdater.java:207)
	at com.intellij.openapi.actionSystem.impl.ActionUpdateEdtExecutor.lambda$computeOnEdt$0(ActionUpdateEdtExecutor.java:45)
	at com.intellij.openapi.actionSystem.impl.Utils.lambda$expandActionGroupFastTrack$5(Utils.java:272)
	at com.intellij.openapi.actionSystem.impl.Utils.runLoopAndWaitForFuture(Utils.java:603)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroupFastTrack(Utils.java:270)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroupImpl(Utils.java:182)
	at com.intellij.openapi.actionSystem.impl.Utils.lambda$fillMenu$6(Utils.java:296)
	at com.intellij.openapi.actionSystem.impl.Utils.computeWithRetries(Utils.java:641)
	at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:295)
	at com.intellij.openapi.actionSystem.impl.ActionMenu.fillMenu(ActionMenu.java:411)
	at com.intellij.openapi.actionSystem.impl.ActionMenu.setPopupMenuVisible(ActionMenu.java:360)
	at java.desktop/javax.swing.JPopupMenu.menuSelectionChanged(JPopupMenu.java:1484)
	at java.desktop/javax.swing.MenuSelectionManager.setSelectedPath(MenuSelectionManager.java:129)
	at java.desktop/javax.swing.plaf.basic.BasicMenuUI.appendPath(BasicMenuUI.java:258)
	at java.desktop/javax.swing.plaf.basic.BasicMenuUI$Actions.actionPerformed(BasicMenuUI.java:316)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:317)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:249)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by hurricup** [comment]
The issue is that we are trying to get a local path from the bad context.
