### ISSUE TITLE
Rider 2022.3: Issue with XSubs deparse (different project model)

### ISSUE THREAD

**Issue by Zastai** [Camelcade/Perl5-IDEA#2548]
IDE: Rider 2022.3 (Build #RD-223.7571.232, built on December 5, 2022)
Perl5 Plugin: 2022.3
JRE Version: as bundled with Rider
OS: Windows 10 (22H2, build 19045.2251)

After updating to Rider 2022.3, and similarly updating the Perl plugin, I get the "XSubs Change Detected" notification; that's fairly standard in and of itself.
However, after clicking Regenerate and waiting for that the finish, I get another notification: "Error Creating XSubs Result File": "Could not find suitable content root for creating a file: _Deparsed_XSubs.pm".
Rider does not have any UI for content roots, that IntelliJ concept is hidden from the user, to present UX more closely resembling Visual Studio (you open the solution, and Rider creates IntelliJ style projects behind the scenes in a .idea folder - it doesn't even seem to use any modules), so I am not sure what I can do about this.

**Comment by hurricup** [comment]
Logs may be helpful with this. They may contain additional information.

**Comment by Zastai** [comment]
The logs show

```
2022-12-13 16:31:33,846 [  83682]   INFO - #com.perl5.lang.perl.xsubs.PerlXSubsState - Deparsing finished with exit code: 0. STDERR:
Error loading DBD::Oracle:
Can't load 'C:/Strawberry/perl/vendor/lib/auto/DBD/Oracle/Oracle.xs.dll' for module DBD::Oracle: load_file:The specified module could not be found at C:/Strawberry/perl/lib/DynaLoader.pm line 193.
*** at (eval 270) line 1.
Compilation failed in require at (eval 270) line 1.

Error loading Filter::decrypt:
Aborting, Compiler detected at C:/Strawberry/perl/lib/XSLoader.pm line 111.
Compilation failed in require at (eval 604) line 1.

unexpected OP_COREARGS at C:/Strawberry/perl/lib/B/Deparse.pm line 1663.
unexpected OP_COREARGS at C:/Strawberry/perl/lib/B/Deparse.pm line 1663.
```

(where `***` is a NUL byte), which looks fine enough.

That's followed by ~1500 lines like

```
2022-12-13 16:31:33,856 [  83692]   WARN - #com.perl5.lang.perl.xsubs.PerlXSubsState - Unable to create _Deparsed_XSubs.pm in the content root file://C:/path/to/project/MyProject.sln of the module Module: 'rider.module'cause: 'C:/path/to/project/MyProject.sln' is not a directory in VFS
```

(i.e. one for every file in my project), finally followed by:

```
2022-12-13 16:31:33,956 [  83792]   WARN - #com.perl5.lang.perl.xsubs.PerlXSubsState - Error creating deparsed file
java.io.IOException: Could not find suitable content root for creating a file: _Deparsed_XSubs.pm
	at com.perl5.lang.perl.xsubs.PerlXSubsState.getOrCreateDeparsedSubsFile(PerlXSubsState.java:219)
	at com.perl5.lang.perl.xsubs.PerlXSubsState$2.lambda$run$1(PerlXSubsState.java:318)
	at com.intellij.openapi.application.WriteAction.lambda$run$1(WriteAction.java:86)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:943)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:969)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:85)
	at com.perl5.lang.perl.xsubs.PerlXSubsState$2.lambda$run$2(PerlXSubsState.java:313)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:429)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:97)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:74)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:114)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:36)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:774)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

So it looks like Rider makes every file in the project a separate "content root" as far as the IntelliJ model is concerned.

**Comment by hurricup** [comment]
oh, so for rider this is a solution file. This is unexpected...

**Comment by hurricup** [comment]
This is caused by f62f048fa34cbf5fe84f8a1e5a60d08769618f0b
Was not expecting to have a non-directory in there, investigating.
As workaround you may try to create a `_Deparsed_XSubs.pm` file in the root of some module and start deparsing again. Still not sure how rider works with content roots, but probably will work.

**Comment by Zastai** [comment]
> As workaround you may try to create a `_Deparsed_XSubs.pm` file in the root of some module and start deparsing again. Still not sure how rider works with content roots, but probably will work.

Unfortunately not - the file is (still) there. But because it's not a member of the solution or any of its projects (and as a local generated file it shouldn't be), Rider doesn't include it in its content root(s).

Perhaps you could check for a projects with a single module called "rider.module" where the first content root is a file whose name ends in `.sln`, and then use the directory part of that file name? (No idea whether the IntelliJ SDK provides anything that would help determine that it's Rider, with specialized API.)

Note that I'd welcome it being stored elsewhere (is it an option to store it in the project metadata (e.g. `.idea/perl5/_Deparsed_XSubs.pm`)?

**Comment by hurricup** [comment]
I'd like to make it work IDE agnostic, without IDE specific hacks. Probably I have a solution, but you'll need to try it, because i have no software necessary to run rider. Stay tuned.

**Comment by hurricup** [comment]
After tests will pass on https://github.com/Camelcade/Perl5-IDEA/actions/runs/3694286737 you will be able to download zip file with plugin. Just use `install from disk` to test.

**Comment by Zastai** [comment]
Looks like that build requires Rider EAP (trying to install it says it needs 223.8214 or later, but my released Rider is RD-223.7571.232). Will see if I can install the EAP side by side; I'm not willing to _replace_ my Rider with an EAP version.

**Comment by hurricup** [comment]
Here is the build for 2022.3
[plugin-2022.3.rider_test.zip](https://github.com/Camelcade/Perl5-IDEA/files/10233601/plugin-2022.3.rider_test.zip)

**Comment by Zastai** [comment]
With that one I do indeed get "XSubs deparsing finished", and the file that was there has an updated timestamp.

Maybe it would make sense to log a trace or info level message indicating what file was actually used - currently I only see the Deparsing finished-with-stdout/stderr message, so I can't know for sure which file it saved the results in.

**Comment by hurricup** [comment]
You may try to create a script in the project and try to invoke completion for something from deparsed file. or see if resolve works.
