### ISSUE TITLE
Profiler UI leaking thread when tests are profiled

### ISSUE THREAD

**Issue by hurricup** [Camelcade/Perl5-IDEA#2613]
```
Leaking threads dump:?
"AsyncPanelWithEmptyText" (alive) TIMED_WAITING?
	at java.base/jdk.internal.misc.Unsafe.park(Native Method)?
	at java.base/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:410)?
	at com.intellij.openapi.progress.impl.CoreProgressManager.sleepIfNeededToGivePriorityToAnotherThread(CoreProgressManager.java:839)?
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runCheckCanceledHooks(ProgressManagerImpl.java:191)?
	at com.intellij.openapi.progress.impl.CoreProgressManager.doCheckCanceled(CoreProgressManager.java:145)?
	at com.intellij.openapi.progress.ProgressManager.checkCanceled(ProgressManager.java:227)?
	at com.intellij.profiler.model.CalleesListModelBuilder.collectCallees(CalleesListModelBuilder.kt:37)?
	at com.intellij.profiler.model.CalleesListModelBuilder.calleesList(CalleesListModelBuilder.kt:26)?
	at com.intellij.profiler.model.CalleesListModelBuilder.calleesList(CalleesListModelBuilder.kt:17)?
	at com.intellij.profiler.model.BaseRichCallTreeModel.allCalleesList(RichCallTreeModel.kt:367)?
	at com.intellij.profiler.ui.MainMethodsListComponent$update$1.invoke(MainMethodsListComponent.kt:81)?
	at com.intellij.profiler.ui.MainMethodsListComponent$update$1.invoke(MainMethodsListComponent.kt:81)?
	at com.intellij.profiler.ui.CalleesListComponent.setDataAsync$lambda$2(CalleesListComponent.kt:128)?
	at com.intellij.profiler.ui.concurrency.EdtWorker.lambda$updateAsync$1(EdtWorker.java:76)?
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)?
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)?
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)?
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)?
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)?
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)?
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)?
	at com.intellij.profiler.ui.concurrency.EdtWorker.lambda$updateAsync$2(EdtWorker.java:91)?
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:248)?
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:28)?
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:221)?
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:227)?
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:210)?
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)?
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)?
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:740)?
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:737)?
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)?
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:737)?
	at java.base/java.lang.Thread.run(Thread.java:1589)?
```

**Comment by hurricup** [comment]
This is IDE problem, so this issue is for the reference
