### ISSUE TITLE
WSL: Failed to Fetch Perl Version

### ISSUE THREAD

**Issue by rwp0** [Camelcade/Perl5-IDEA#2689]
![image](https://github.com/Camelcade/Perl5-IDEA/assets/68062695/c9255c5d-a7e7-47bb-939a-9af784699245)

Where can I view the logs?

On Windows 11 with EAP Perl Plugin (and IntelliJ IDEA Community)

**Comment by hurricup** [comment]
`Help -> Show logs in Files`

**Comment by rwp0** [comment]
> `Help -> Show logs in Files`

For me it's called: `Show log in Explorer`

---

Here's the log:

```
2023-06-02 12:06:59,466 [44046735]   INFO - #com.perl5.lang.perl.idea.execution.PerlCommandLine - Executing: //wsl$/Ubuntu/usr/local/bin/perl5.37.12 -MConfig -e "print q{perl}.chr(10);do {print;print chr(10)} for @Config{qw/version archname/}"
2023-06-02 12:06:59,467 [44046736]   INFO - #com.perl5.lang.perl.idea.execution.PerlCommandLine -   environment: {} (+CONSOLE)
2023-06-02 12:06:59,467 [44046736]   INFO - #com.perl5.lang.perl.idea.execution.PerlCommandLine -   working dir: null
2023-06-02 12:06:59,467 [44046736]   INFO - #com.perl5.lang.perl.idea.execution.PerlCommandLine -   host = local; vm = system; pty = false; charset: windows-1252
2023-06-02 12:06:59,501 [44046770]   WARN - #com.perl5.lang.perl.util.PerlRunUtil - Error executing //wsl$/Ubuntu/usr/local/bin/perl5.37.12 [-MConfig, -e, print q{perl}.chr(10);do {print;print chr(10)} for @Config{qw/version archname/}]
com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "\\wsl$\Ubuntu\usr\local\bin\perl5.37.12": CreateProcess error=193, %1 is not a valid Win32 application
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:356)
	at com.perl5.lang.perl.idea.execution.PerlCommandLine.createProcess(PerlCommandLine.java:298)
	at com.perl5.lang.perl.idea.sdk.host.local.PerlLocalHostData.createProcess(PerlLocalHostData.java:51)
	at com.perl5.lang.perl.idea.sdk.host.PerlHostData.doCreateProcessHandler(PerlHostData.java:131)
	at com.perl5.lang.perl.idea.sdk.host.PerlHostData.createProcessHandler(PerlHostData.java:272)
	at com.perl5.lang.perl.idea.sdk.host.PerlHostData.execAndGetOutput(PerlHostData.java:249)
	at com.perl5.lang.perl.util.PerlRunUtil.getOutputFromProgram(PerlRunUtil.java:413)
	at com.perl5.lang.perl.util.PerlRunUtil.getOutputFromProgram(PerlRunUtil.java:405)
	at com.perl5.lang.perl.idea.sdk.PerlSdkType.getPerlVersionDescriptor(PerlSdkType.java:266)
	at com.perl5.lang.perl.idea.sdk.PerlSdkType.createSdk(PerlSdkType.java:306)
	at com.perl5.lang.perl.idea.sdk.PerlSdkType.createAndAddSdk(PerlSdkType.java:287)
	at com.perl5.lang.perl.idea.sdk.versionManager.system.PerlSystemHandler.lambda$createSdkInteractively$2(PerlSystemHandler.java:77)
	at com.perl5.lang.perl.idea.sdk.host.PerlHostHandler.lambda$chooseFileInteractively$0(PerlHostHandler.java:90)
	at com.perl5.lang.perl.idea.sdk.host.PerlHostHandler.chooseFileInteractively(PerlHostHandler.java:180)
	at com.perl5.lang.perl.idea.sdk.host.PerlHostHandler.chooseFileInteractively(PerlHostHandler.java:92)
	at com.perl5.lang.perl.idea.sdk.versionManager.system.PerlSystemHandler.createSdkInteractively(PerlSystemHandler.java:66)
	at com.perl5.lang.perl.idea.configuration.settings.sdk.Perl5SdkConfigurable$2$1.run(Perl5SdkConfigurable.java:132)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:431)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:115)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$9(CoreProgressManager.java:516)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:89)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:255)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$1(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:255)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$19(ProgressRunner.java:480)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.IOException: Cannot run program "\\wsl$\Ubuntu\usr\local\bin\perl5.37.12": CreateProcess error=193, %1 is not a valid Win32 application
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:432)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:346)
	... 39 more
Caused by: java.io.IOException: CreateProcess error=193, %1 is not a valid Win32 application
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:499)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:158)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 42 more
2023-06-02 12:06:59,501 [44046770]   WARN - #com.perl5.lang.perl.idea.sdk.PerlSdkType - Got inappropriate response from perl: 
```

I tested with the system Perl version as well which is v5.34.0 on Ubuntu 22.04.2 LTS with the same error message dialog appearing.

**Comment by hurricup** [comment]
it is. you added perl from wsl as local interpreter. you can't do that. there is a separate menu item to add wsl interpreter.

**Comment by rwp0** [comment]
> it is. you added perl from wsl as local interpreter. you can't do that. there is a separate menu item to add wsl interpreter.

I don't seem to have that menu.

![image](https://github.com/Camelcade/Perl5-IDEA/assets/68062695/e5d4a9b8-60a5-4b78-9b9f-36e21048755b)

Could you please tell me where I can find that?

**Comment by rwp0** [comment]
Seems like the plugin doesn't detect WSLv2 with IDEA EAP on Windows 11 for some reason 🤔

**Comment by hurricup** [comment]
OH, sorry, missed that, but it works only in commercial ides, IDEA Ultimate in your case. Won't work in community.

**Comment by rwp0** [comment]
> commercial

That's sad 😢 

It must be related to [WSL Support Framework](https://plugins.jetbrains.com/plugin/10024-wsl-support-framework) plugin's compatibility warning I already saw elsewhere:
> Not compatible with the version of your running IDE (IntelliJ IDEA 2023.2 EAP)

Fortunately Visual Studio Code supports WSL without restrictions.
