### ISSUE TITLE
Seems reproducible SOE on type inferrence

### ISSUE THREAD

**Issue by hurricup** [Camelcade/Perl5-IDEA#2792]
Build: IU-232.10203.10
OS: Linux amd64 6.2.0-36-generic
Java Vendor: JetBrains s.r.o.
Java Version: 17.0.8.1
Java Runtime Version: 17.0.8.1+7-b1000.32
Perl Plugin Version: 232.8453.116-EAP-SNAPSHOT
Description: <none>
Message: *** exception class was changed or removed
```
Error while indexing /home/hurricup/Projects/IDEA-Perl5/plugin/src/test/resources/unit/perl/stubs/hugeList.pl
To reindex this file IDEA has to be restarted
   
   java.lang.StackOverflowError
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.checkCanceled(AbstractProgressIndicatorBase.java:150)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorExBase.checkCanceled(AbstractProgressIndicatorExBase.java:89)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorExBase.delegate(AbstractProgressIndicatorExBase.java:202)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorExBase.checkCanceled(AbstractProgressIndicatorExBase.java:91)
	at com.intellij.ide.util.DelegatingProgressIndicator.checkCanceled(DelegatingProgressIndicator.java:135)
	at com.intellij.openapi.progress.util.ProgressWrapper.checkCanceled(ProgressWrapper.java:81)
	at com.intellij.openapi.progress.impl.CoreProgressManager.doCheckCanceled(CoreProgressManager.java:141)
	at com.intellij.openapi.progress.ProgressManager.checkCanceled(ProgressManager.java:231)
	at com.intellij.openapi.progress.ProgressIndicatorProvider.checkCanceled(ProgressIndicatorProvider.java:23)
	at com.intellij.psi.impl.source.tree.CompositeElement.getPsi(CompositeElement.java:676)
	at com.intellij.psi.impl.source.SourceTreeToPsiMap.treeElementToPsi(SourceTreeToPsiMap.java:15)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.getLastChild(SharedImplUtil.java:41)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.getLastChild(ASTDelegatePsiElement.java:89)
	at com.perl5.lang.perl.psi.utils.PerlResolveUtil.processChildren(PerlResolveUtil.java:89)
	at com.perl5.lang.perl.psi.impl.PerlCompositeElementImpl.processDeclarations(PerlCompositeElementImpl.java:43)
	at com.perl5.lang.perl.psi.utils.PerlResolveUtil.processChildren(PerlResolveUtil.java:94)
	at com.perl5.lang.perl.psi.impl.PerlCompositeElementImpl.processDeclarations(PerlCompositeElementImpl.java:43)

```

**Comment by hurricup** [comment]
https://camelcade.myjetbrains.com/youtrack/issue/CAMELCADE-14207/Error-while-indexing-home-hurricup-Projects-IDEA-Perl5-plugin-src-test-resou
