### ISSUE TITLE
Plugin throws an exception about perl interpreter when running configuration

### ISSUE THREAD

**Issue by hurricup** [Camelcade/Perl5-IDEA#2841]
This is strange. I assume it should be user-visible error, not an exception. 

```
com.intellij.execution.ExecutionException: Unable to detect perl interpreter for a project app
	at com.perl5.lang.perl.idea.run.GenericPerlRunConfiguration.getEffectiveSdk(GenericPerlRunConfiguration.java:159)
	at com.perl5.lang.perl.idea.run.GenericPerlRunConfiguration.createBaseCommandLine(GenericPerlRunConfiguration.java:404)
	at com.perl5.lang.perl.idea.run.GenericPerlRunConfiguration.createCommandLine(GenericPerlRunConfiguration.java:359)
	at com.perl5.lang.perl.idea.run.PerlRunProfileState.createCommandLine(PerlRunProfileState.java:70)
	at com.perl5.lang.perl.idea.run.PerlRunProfileState.startProcess(PerlRunProfileState.java:66)
	at com.perl5.lang.perl.idea.run.PerlRunProfileState.execute(PerlRunProfileState.java:53)
	at com.perl5.lang.perl.idea.run.PerlRunProfileState.execute(PerlRunProfileState.java:45)
	at com.perl5.lang.perl.idea.run.run.PerlRunProgramRunner.doExecute(PerlRunProgramRunner.java:48)
	at com.perl5.lang.perl.idea.run.GenericPerlProgramRunner.lambda$execute$0(GenericPerlProgramRunner.java:66)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

https://camelcade.myjetbrains.com/youtrack/issue/CAMELCADE-18053

**Comment by hurricup** [comment]
https://camelcade.myjetbrains.com/youtrack/issue/CAMELCADE-18245
