### ISSUE TITLE
Exception while reading wsl config

### ISSUE THREAD

**Issue by hurricup** [Camelcade/Perl5-IDEA#2895]
https://camelcade.myjetbrains.com/youtrack/issue/CAMELCADE-20338/java.lang.IllegalStateException-There-is-no-ProgressIndicator-or-Job-in-this-th
```
java.lang.IllegalStateException: There is no ProgressIndicator or Job in this thread, the current job is not cancellable.
	at com.intellij.openapi.progress.CoroutinesKt$runBlockingCancellable$1.invoke(coroutines.kt:141)
	at com.intellij.openapi.progress.CoroutinesKt$runBlockingCancellable$1.invoke(coroutines.kt:139)
	at com.intellij.openapi.progress.ContextKt.prepareThreadContext(context.kt:85)
	at com.intellij.openapi.progress.CoroutinesKt.runBlockingCancellable(coroutines.kt:139)
	at com.intellij.openapi.progress.CoroutinesKt.runBlockingCancellable(coroutines.kt:122)
	at com.intellij.execution.wsl.WslIjentUtil.runProcessBlocking(WslIjentUtil.kt:64)
	at com.intellij.execution.wsl.WSLDistribution.lambda$patchCommandLine$2(WSLDistribution.java:241)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:463)
	at com.intellij.execution.configurations.PtyCommandLine.createProcess(PtyCommandLine.java:125)
	at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:469)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:374)
	at com.perl5.lang.perl.idea.execution.PerlCommandLine.createProcess(PerlCommandLine.java:306)
	at com.perl5.lang.perl.idea.sdk.host.wsl.PerlWslData.createProcess(PerlWslData.java:168)
	at com.perl5.lang.perl.idea.sdk.host.PerlHostData.createConsoleProcess(PerlHostData.java:124)
	at com.perl5.lang.perl.idea.sdk.host.PerlHostData.doCreateConsoleProcessHandler(PerlHostData.java:102)
	at com.perl5.lang.perl.idea.sdk.host.PerlHostData.createConsoleProcessHandler(PerlHostData.java:305)
	at com.perl5.lang.perl.idea.run.PerlRunProfileState.startProcess(PerlRunProfileState.java:66)
	at com.perl5.lang.perl.idea.run.PerlRunProfileState.execute(PerlRunProfileState.java:53)
	at com.perl5.lang.perl.idea.run.PerlRunProfileState.execute(PerlRunProfileState.java:45)
	at com.perl5.lang.perl.idea.run.run.PerlRunProgramRunner.doExecute(PerlRunProgramRunner.java:48)
	at com.perl5.lang.perl.idea.run.GenericPerlProgramRunner.lambda$execute$0(GenericPerlProgramRunner.java:66)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by rwp0** [comment]
> https://camelcade.myjetbrains.com/youtrack/issue/CAMELCADE-20338/java.lang.IllegalStateException-There-is-no-ProgressIndicator-or-Job-in-this-th

Can wee see it?

![image](https://github.com/user-attachments/assets/340a3c1a-0b55-484f-bf19-4277e7e66f1d)
