### ISSUE TITLE
Exception when doing an undo with latest IDEA

### ISSUE THREAD

**Issue by murdegern** [Camelcade/Perl5-IDEA#2928]
IntelliJ IDEA, Build #IU-242.23726.103, built on October 23, 2024

Perl Plugin 242.5944

JRE - I think this one was brought by IDEA itself, in Help => About it says

Runtime version: 21.0.4+13-b509.26 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

My system java is
openjdk version "23" 2024-09-17
OpenJDK Runtime Environment (build 23)
OpenJDK 64-Bit Server VM (build 23, mixed mode, sharing)

OS: arch linux on x86_64, everything updated to current version.

I get the following exception if I hit "u" for undo:

java.lang.Throwable: com.perl5.lang.perl.lexer.PerlBaseLexer <clinit> requests com.perl5.lang.perl.fileTypes.PerlFileTypeService instance. Class initialization must not depend on services. Consider using instance of the service on-demand instead.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.serviceContainer.ComponentManagerImplKt.checkOutsideClassInitializer(ComponentManagerImpl.kt:1588)
	at com.intellij.serviceContainer.ComponentManagerImplKt.getOrCreateInstanceBlocking(ComponentManagerImpl.kt:1557)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:746)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:690)
	at com.perl5.lang.perl.fileTypes.PerlFileTypeService.getInstance(PerlFileTypeService.java:76)
	at com.perl5.lang.perl.util.PerlPluginUtil.getUnloadAwareDisposable(PerlPluginUtil.java:48)
	at com.perl5.lang.perl.lexer.PerlBaseLexer.<clinit>(PerlBaseLexer.java:83)
	at com.perl5.lang.perl.lexer.adapters.PerlSublexingLexerAdapter.<init>(PerlSublexingLexerAdapter.java:83)
	at com.perl5.lang.perl.lexer.adapters.PerlMergingLexerAdapter.<init>(PerlMergingLexerAdapter.java:37)
	at com.perl5.lang.perl.idea.highlighter.PerlSyntaxHighlighter.getHighlightingLexer(PerlSyntaxHighlighter.java:207)
	at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter.<init>(LexerEditorHighlighter.java:59)
	at com.intellij.openapi.editor.ex.util.LayeredLexerEditorHighlighter.<init>(LayeredLexerEditorHighlighter.java:43)
	at com.perl5.lang.perl.idea.highlighter.PerlEditorHighlighterProviderBase.getEditorHighlighter(PerlEditorHighlighterProviderBase.java:43)
	at com.intellij.openapi.editor.highlighter.EditorHighlighterFactoryImpl.createEditorHighlighter(EditorHighlighterFactoryImpl.kt:52)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorProvider$createFileEditor$2$highlighterDeferred$1$highlighter$1.invoke(PsiAwareTextEditorProvider.kt:69)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorProvider$createFileEditor$2$highlighterDeferred$1$highlighter$1.invoke(PsiAwareTextEditorProvider.kt:68)
	at com.intellij.openapi.application.rw.InternalReadAction.insideReadAction(InternalReadAction.kt:104)
	at com.intellij.openapi.application.rw.InternalReadAction.access$insideReadAction(InternalReadAction.kt:15)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadBlocking$2.invoke$lambda$0(InternalReadAction.kt:85)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:291)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:965)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadBlocking$2.invoke(InternalReadAction.kt:84)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadBlocking$2.invoke(InternalReadAction.kt:82)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContextInner(coroutines.kt:339)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invokeSuspend(coroutines.kt:232)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invoke(coroutines.kt)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invoke(coroutines.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:261)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:231)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadBlocking(InternalReadAction.kt:82)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadAction(InternalReadAction.kt:74)
	at com.intellij.openapi.application.rw.InternalReadAction.readLoop(InternalReadAction.kt:64)
	at com.intellij.openapi.application.rw.InternalReadAction.access$readLoop(InternalReadAction.kt:15)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invokeSuspend(InternalReadAction.kt:43)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invoke(InternalReadAction.kt)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invoke(InternalReadAction.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.openapi.application.rw.InternalReadAction.runReadAction(InternalReadAction.kt:39)
	at com.intellij.openapi.application.rw.PlatformReadWriteActionSupport.executeReadAction(PlatformReadWriteActionSupport.kt:38)
	at com.intellij.openapi.application.ReadWriteActionSupport.executeReadAction$default(ReadWriteActionSupport.kt:15)
	at com.intellij.openapi.application.CoroutinesKt.constrainedReadActionBlocking(coroutines.kt:124)
	at com.intellij.openapi.application.CoroutinesKt.readActionBlocking(coroutines.kt:93)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorProvider$createFileEditor$2$highlighterDeferred$1.invokeSuspend(PsiAwareTextEditorProvider.kt:68)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)

Thanks for any help!

**Comment by hurricup** [comment]
This was fixed in https://github.com/Camelcade/Perl5-IDEA/commit/45ee4b2488beb179b885c30e678511d7c2897bbf please, updated to the most recent version of the plugin.

**Comment by murdegern** [comment]
Thanks! I only tried to update via the "Check for updates" menu entry, now that I downloaded the plugin and installed from disk, the exception is gone (as you wrote).
